### ISSUE TITLE
Very slow to start proxy

### ISSUE THREAD

**Issue by jk2K** [BrowserSync/browser-sync#1081]
### Issue details
Very slow to start proxy

### Steps to reproduce/test case

1. Run gulp
```bash
$ gulp
```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.12.5  ]
- Node        [  v6.0.0  ]
- Npm         [  3.8.6  ]

`package.json`
```json
{
  "dependencies": {
    "babel-register": "^6.7.2",
    "babel-runtime": "^6.6.1",
    "koa": "^2.0.0",
    "koa-nunjucks-2": "^3.0.0-alpha.2",
    "koa-router": "^7.0.1",
    "koa-static": "^3.0.0"
  },
  "devDependencies": {
    "babel-plugin-transform-runtime": "^6.7.5",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-stage-3": "^6.5.0",
    "browser-sync": "^2.12.5",
    "gulp": "^3.9.1",
    "gulp-nodemon": "^2.0.6"
  }
}
```

### Affected platforms

- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

`app.js`
```javascript
const Koa = require('koa');
const router = require('koa-router')();
const serve = require('koa-static');
const koaNunjucks = require('koa-nunjucks-2');
const path = require('path');
const app = new Koa();

//  template
app.use(koaNunjucks({
    ext: 'html',
    path: path.join(__dirname, '/views'),
    nunjucksConfig: {
        autoescape: true
    }
}));

// expose css, js, img, font
app.use(serve(__dirname + '/assets'));

// x-response-time
app.use(async function (ctx, next) {
    const start = new Date();
    await next();
    const ms = new Date() - start;
    ctx.set('X-Response-Time', `${ms}ms`);
});

// index
router.get('/', function (ctx, next) {
    ctx.render('index');
});

app.use(router.routes())
    .use(router.allowedMethods());

app.listen(8000);
```
`start.js`
```javascript
require('babel-register');
require('./app/app');
```
`gulpfile.js`
```javascript
var gulp = require('gulp');
var nodemon = require('gulp-nodemon');
var browserSync = require('browser-sync').create();

gulp.task('nodemon', function () {
    // check whether nodemon is first started
    var firstStart = true;
    
    browserSync.init({
        proxy: "localhost:8000",
        browser: "google chrome"
    });
    
    return nodemon({
        script: 'start.js'
    })
        .on('start', function () {
            // reload;
            if (!firstStart) {
                browserSync.reload();
            } else {
                firstStart = false;
            }
        });
});

gulp.task('default', ['nodemon']);
```

## Update 2016.5.6
I change `proxy-server.js`, in line 111
```javascript
/**
* Handle Proxy errors
*/
proxy.on("error", function (err) {
    console.log(err);
    if (typeof opt.get("errHandler") === "function") {
        opt.get("errHandler").call(null, err);
    }
});
```
Now gets the error when bs reloading browsers
```
{ Error: connect ECONNREFUSED 127.0.0.1:8000
    at Object.exports._errnoException (util.js:896:11)
    at exports._exceptionWithHostPort (util.js:919:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1073:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8000 }
```

**Comment by jk2K** [comment]
fixed,  `browser-sync` need to wait before instructing the browser to reload.
```
browserSync.init({
    proxy: "localhost:8000",
    reloadDelay: 2000,
    browser: "google chrome"
});
```
