### ISSUE TITLE
TypeError: Object #<Set> has no method 'forEach'

### ISSUE THREAD

**Issue by chihuahua** [BrowserSync/browser-sync#1116]
### Issue details

Calling `require('browser-sync')` triggers an error:
```
chizeng@chizeng:~/Desktop/bloop$ gulp 
TypeError: Object #<Set> has no method 'forEach'
    at setToArray (/usr/local/home/chizeng/Desktop/bloop/node_modules/browser-sync/lodash.custom.js:556:9)
    at Object.<anonymous> (/usr/local/home/chizeng/Desktop/bloop/node_modules/browser-sync/lodash.custom.js:2251:33)
    at Object.<anonymous> (/usr/local/home/chizeng/Desktop/bloop/node_modules/browser-sync/lodash.custom.js:4243:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/home/chizeng/Desktop/bloop/node_modules/browser-sync/lib/hooks.js:3:20)
```

### Steps to reproduce/test case

Run `npm install browser-sync --save-dev` for a project on an ubuntu machine.
Or run `npm install` for this project. https://github.com/chihuahua/bloop
Require `browser-sync` in gulpfile.js and run some gulp command such as the default one.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.12.10]
- Node             [0.10.25]
- Npm              [1.3.10]

### Affected platforms
linux

### Browsersync use-case

- Gulp

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

The error surfaces when I require `browser-sync`:
```
require('harmonize')();
var browserSyncRequired = require('browser-sync');
var browserSync = browserSyncRequired.create();
var gulp = require('gulp');
var change = require('gulp-change');
var closureCompiler = require('gulp-closure-compiler');
var closureCssRenamer = require('gulp-closure-css-renamer');
var concat = require('gulp-concat');
var htmlmin = require('gulp-htmlmin');
var less = require('gulp-less');
var util = require('gulp-util');
var argv = require('yargs').argv;
```

**Comment by chihuahua** [comment]
Updating node from 0.10.25 to 4.4.5 (the current version as of this writing) solved this.
