### ISSUE TITLE
  Page error (connect ECONNREFUSED 127.0.0.1:3000): http://localhost:3000

### ISSUE THREAD

**Issue by fivedoor** [BrowserSync/browser-sync#1148]
### Issue details

I am encountering the following error when trying to use the check-pages package with browserSync. 
```

[21:58:19] Starting 'checkDev'...
Checked 1 page and 0 links, found 1 issue.
Summary of issues:
 http://localhost:3000
  Page error (connect ECONNREFUSED 127.0.0.1:3000): http://localhost:3000 (24ms)

[21:58:20] 'checkDev' errored after 1.24 s
[21:58:20] Error: 1 issue.
    at /Users/fivedoor/Documents/development/fivedoor-email-frame/node_modules/check-pages/checkPages.js:426:13
    at next (/Users/fivedoor/Documents/development/fivedoor-email-frame/node_modules/check-pages/checkPages.js:435:5)
    at Request._callback (/Users/fivedoor/Documents/development/fivedoor-email-frame/node_modules/check-pages/checkPages.js:314:9)
    at self.callback (/Users/fivedoor/Documents/development/fivedoor-email-frame/node_modules/check-pages/node_modules/request/request.js:200:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/Users/fivedoor/Documents/development/fivedoor-email-frame/node_modules/check-pages/node_modules/request/request.js:831:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

When I tested with `gulp-connect` to initiate a server (in place of browserSync) then I no longer come up against the ECONNREFUSED error. 

Hoping someone can help pinpoint the issue/ a solution? 

The issue is also logged here:
https://github.com/DavidAnson/check-pages/issues/7

### What I have also tried:

- Both the following work (while I have browserSync initiated I see my index page on both):
http://localhost:3000/
http://127.0.0.1:3000/

- updated to latest version of browsersync
- updated unmet peer dependencies
- Tried testing with legacy versions of browsersync and check-pages
- Checked the ports availability with `netstat -a.` 3000 is not by the looks of it already in use
- Tried  `npm cache clean` then retested with same results
- Tried `curl http://localhost:3000 -v` which results in 

```
* Rebuilt URL to: http://localhost:3000/
*   Trying ::1...
* connect to ::1 port 3000 failed: Connection refused
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 3000 failed: Connection refused
* Failed to connect to localhost port 3000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 3000: Connection refused
```
- `curl 0.0.0.0:3000 `results in: `curl: (52) Empty reply from server`

### Steps to reproduce/test case

Running the following gulp task via terminal:
```
var checkPages = require("check-pages");

gulp.task("checkDev", ['bs'], function(callback) {
  var options = {
    pageUrls: [
      'http://localhost:3000'
    ],
    checkLinks: true,
    
    noEmptyFragments: true,
    noLocalLinks: true,
    noRedirects: true,
    onlySameDomain: true,
    preferSecure: true,
    queryHashes: true,
    checkCaching: true,
    checkCompression: true,
    checkXhtml: true,
    summary: true,
    terse: true,
    maxResponseTime: 200,
    userAgent: 'custom-user-agent/1.2.3'
  };
  checkPages(console, options, callback);
});

```

### Browsersync task
```

var bs = require('browser-sync').create();

gulp.task('bs', function() {

  bs.init({
    server: {
      baseDir: 'src'
    }
  });

});

```

###  Version of Browsersync, node and npm you're running

- Browsersync [  2.13.0  ]
- check-pages [ 0.10.0 ]
- Node        [  v4.4.3  ]
- Npm         [  3.8.9 ]

### Affected platforms

-  OS X 10.11.4

### Browsersync use-case

- Gulp 3.9.1

Thanks

**Comment by josephdpurcell** [comment]
For my issue, I was able to add `--listen 0.0.0.0` to resolve the issue, see https://github.com/BrowserSync/browser-sync/issues/799#issuecomment-1341755178.
