### ISSUE TITLE
Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by mganand** [BrowserSync/browser-sync#1180]
`C:\Users\MohanKumar\coursera-test\site>browser-sync start --server --directory -
-files "*"
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EPERM: operation not permitted, open 'C:\Users\MohanKumar\AppData\Roaming
\npm\node_modules\browser-sync\node_modules\eazy-logger\node_modules\tfunk\node_
modules\chalk\node_modules\strip-ansi\node_modules\ansi-regex\index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.Module._extensions..js (module.js:415:20)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\MohanKumar\AppData\Roaming\npm\node_modules\
browser-sync\node_modules\eazy-logger\node_modules\tfunk\node_modules\chalk\node
_modules\strip-ansi\index.js:2:17)
    at Module._compile (module.js:409:26)`
This is my problem with browser sync when i tried to run this command it keeps on repeating any help??

**Comment by mganand** [comment]
https://github.com/jhu-ep-coursera/fullstack-course4/wiki/Frequently-Asked-Questions-(FAQ)#q-i-am-getting-xmlhttprequest-cannot-load-filesomepath-error-what-am-i-doing-wrong

Do look at the command here. It solved my issue.
