### ISSUE TITLE
Possible breaking change in 2.17.1

### ISSUE THREAD

**Issue by nhaesler** [BrowserSync/browser-sync#1226]
### Issue details

Beginning with 2.17.1 browser-sync throws the following error for me:
```
TypeError: bs.options.get(...).forEach is not a function
    at Object.getSnippetMiddleware (/home/nico/src/tradity-client/node_modules/browser-sync/lib/server/utils.js:201:40)
    at Object.getMiddlewares (/home/nico/src/tradity-client/node_modules/browser-sync/lib/server/utils.js:86:37)
    at Object.getBaseApp (/home/nico/src/tradity-client/node_modules/browser-sync/lib/server/utils.js:175:39)
    at createServer (/home/nico/src/tradity-client/node_modules/browser-sync/lib/server/static-server.js:73:27)
    at createServer (/home/nico/src/tradity-client/node_modules/browser-sync/lib/server/index.js:91:42)
    at module.exports.plugin (/home/nico/src/tradity-client/node_modules/browser-sync/lib/server/index.js:16:20)
    at Object.startServer [as fn] (/home/nico/src/tradity-client/node_modules/browser-sync/lib/async.js:195:52)
    at /home/nico/src/tradity-client/node_modules/browser-sync/lib/browser-sync.js:149:14
    at iterate (/home/nico/src/tradity-client/node_modules/browser-sync/lib/utils.js:271:13)
    at /home/nico/src/tradity-client/node_modules/browser-sync/lib/utils.js:280:25

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! tradity-client@0.7.0 start: `npm run build && parallelshell 'npm run watch' 'browser-sync start --config bs-config.js'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tradity-client@0.7.0 start script 'npm run build && parallelshell 'npm run watch' 'browser-sync start --config bs-config.js''.
```

Here is the npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.3
3 info using node@v6.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle tradity-client@0.7.0~prestart: tradity-client@0.7.0
6 silly lifecycle tradity-client@0.7.0~prestart: no script for prestart, continuing
7 info lifecycle tradity-client@0.7.0~start: tradity-client@0.7.0
8 verbose lifecycle tradity-client@0.7.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle tradity-client@0.7.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/nico/src/tradity-client/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/nico/Downloads/grails-2.4.4/bin
10 verbose lifecycle tradity-client@0.7.0~start: CWD: /home/nico/src/tradity-client
11 silly lifecycle tradity-client@0.7.0~start: Args: [ '-c',
11 silly lifecycle   'npm run build && parallelshell \'npm run watch\' \'browser-sync start --config bs-config.js\'' ]
12 silly lifecycle tradity-client@0.7.0~start: Returned: code: 1  signal: null
13 info lifecycle tradity-client@0.7.0~start: Failed to exec start script
14 verbose stack Error: tradity-client@0.7.0 start: `npm run build && parallelshell 'npm run watch' 'browser-sync start --config bs-config.js'`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid tradity-client@0.7.0
16 verbose cwd /home/nico/src/tradity-client
17 error Linux 4.4.0-38-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.6.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error tradity-client@0.7.0 start: `npm run build && parallelshell 'npm run watch' 'browser-sync start --config bs-config.js'`
22 error Exit status 1
23 error Failed at the tradity-client@0.7.0 start script 'npm run build && parallelshell 'npm run watch' 'browser-sync start --config bs-config.js''.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the tradity-client package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build && parallelshell 'npm run watch' 'browser-sync start --config bs-config.js'
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs tradity-client
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls tradity-client
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

And here is my bs-config.js:
```

/*
 |--------------------------------------------------------------------------
 | Browser-sync config file
 |--------------------------------------------------------------------------
 |
 | For up-to-date information about the options:
 |   http://www.browsersync.io/docs/options/
 |
 | There are more options than you see here, these are just the ones that are
 | set internally. See the website for more info.
 |
 |
 */
module.exports = {
    "ui": false,
    "files": "dist/**/*",
    "watchOptions": {},
    "server": {
        baseDir: "dist",
        routes: {
            "/node_modules": "node_modules"
        }
    },
    "proxy": false,
    "port": 3000,
    "middleware": require('connect-history-api-fallback')(),
    "serveStatic": [],
    "ghostMode": {
        "clicks": true,
        "scroll": true,
        "forms": {
            "submit": true,
            "inputs": true,
            "toggles": true
        }
    },
    "logLevel": "info",
    "logPrefix": "BS",
    "logConnections": false,
    "logFileChanges": true,
    "logSnippet": true,
    "rewriteRules": false,
    "open": "local",
    "browser": "default",
    "xip": false,
    "hostnameSuffix": false,
    "reloadOnRestart": false,
    "notify": true,
    "scrollProportionally": true,
    "scrollThrottle": 0,
    "scrollRestoreTechnique": "window.name",
    "scrollElements": [],
    "scrollElementMapping": [],
    "reloadDelay": 0,
    "reloadDebounce": 0,
    "plugins": [],
    "injectChanges": true,
    "startPath": null,
    "minify": true,
    "host": null,
    "codeSync": true,
    "timestamps": true,
    "clientEvents": [
        "scroll",
        "scroll:element",
        "input:text",
        "input:toggles",
        "form:submit",
        "form:reset",
        "click"
    ],
    "socket": {
        "socketIoOptions": {
            "log": false
        },
        "socketIoClientConfig": {
            "reconnectionAttempts": 50
        },
        "path": "/browser-sync/socket.io",
        "clientPath": "/browser-sync",
        "namespace": "/browser-sync",
        "clients": {
            "heartbeatTimeout": 5000
        }
    },
    "tagNames": {
        "less": "link",
        "scss": "link",
        "css": "link",
        "jpg": "img",
        "jpeg": "img",
        "png": "img",
        "svg": "img",
        "gif": "img",
        "js": "script"
    }
};
```

All of this is working fine up to and including 2.17.0.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.17.1  ]
- Node        [  6.6.0  ]
- Npm         [  3.10.3  ]

### Affected platforms

- [x] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

### If CLI, please paste the entire command below

browser-sync start --config bs-config.js

**Comment by shakyShane** [comment]
Fixed in `v2.17.2` - thanks for the detailed error report and sorry for any disruption :)
