### ISSUE TITLE
Exception with Node v6.9.1

### ISSUE THREAD

**Issue by joeveiga** [BrowserSync/browser-sync#1244]
### Issue details

    TypeError: Path must be a string. Received undefined
        at assertPath (path.js:7:11)
        at resolve (path.js:186:7)
        at C:\ColdFusion11\cfusion\wwwroot\eMarSuite\client\node_modules\browser-sync\lib\server\static-server.js:47:41
        at Array.map (native)
        at C:\ColdFusion11\cfusion\wwwroot\eMarSuite\client\node_modules\browser-sync\lib\server\static-server.js:43:39
        at updateInDeepMap (C:\ColdFusion11\cfusion\wwwroot\eMarSuite\client\node_modules\immutable\dist\immutable.js:1973:22)
        at updateInDeepMap (C:\ColdFusion11\cfusion\wwwroot\eMarSuite\client\node_modules\immutable\dist\immutable.js:1982:23)
        at Map.updateIn (C:\ColdFusion11\cfusion\wwwroot\eMarSuite\client\node_modules\immutable\dist\immutable.js:1280:26)
        at Map.update (C:\ColdFusion11\cfusion\wwwroot\eMarSuite\client\node_modules\immutable\dist\immutable.js:1272:14)
        at createServer (C:\ColdFusion11\cfusion\wwwroot\eMarSuite\client\node_modules\browser-sync\lib\server\static-server.js:42:10)
        at createServer (C:\ColdFusion11\cfusion\wwwroot\eMarSuite\client\node_modules\browser-sync\lib\server\index.js:91:42)
        at module.exports.plugin (C:\ColdFusion11\cfusion\wwwroot\eMarSuite\client\node_modules\browser-sync\lib\server\index.js:16:20)
        at Object.startServer [as fn] (C:\ColdFusion11\cfusion\wwwroot\eMarSuite\client\node_modules\browser-sync\lib\async.js:195:52)
        at C:\ColdFusion11\cfusion\wwwroot\eMarSuite\client\node_modules\browser-sync\lib\browser-sync.js:149:14
        at iterate (C:\ColdFusion11\cfusion\wwwroot\eMarSuite\client\node_modules\browser-sync\lib\utils.js:271:13)
        at C:\ColdFusion11\cfusion\wwwroot\eMarSuite\client\node_modules\browser-sync\lib\utils.js:280:25

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.17.5  ]
- Node        [  6.9.1  ]
- Npm         [  3.10.8  ]

### Affected platforms

- [ ] linux
- [x] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp [ 3.9.1 ]
- [ ] Grunt
- [ ] CLI

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

    var path = require('path');
    var gulp = require('gulp');
    var conf = require('./conf');

    var browserSync = require('browser-sync');
    var browserSyncSpa = require('browser-sync-spa');

    var util = require('util');
    var proxyMiddleware = require('http-proxy-middleware');

    function browserSyncInit(baseDir, browser) {
        browser = browser === undefined ? 'default' : browser;

        var routes = null;
        if (baseDir === conf.paths.src || (util.isArray(baseDir) && baseDir.indexOf(conf.paths.src) !== -1)) {
            routes = {
                '/bower_components': 'bower_components'
            };
        }

        var server = {
            baseDir: baseDir,
            routes: routes
        };

        server.middleware = proxyMiddleware(['/rest/emarsuite_cfapi/**', '/api/**'],
            {
                target: 'http://localhost:8080',
                changeOrigin: true
            });

        browserSync.instance = browserSync.init({
            //startPath: 'portal/',
            server: server,
            browser: browser,
            port: 3030
        });
    }

    browserSync.use(browserSyncSpa({
        selector: '[ng-app]'// Only needed for angular apps
    }));

    gulp.task('serve', ['watch'], function () {
        browserSyncInit([path.join(conf.paths.tmp, '/serve'), conf.paths.src, , 'bower_components/font-awesome']);
    });

**Comment by joeveiga** [comment]
Nevermind, was a problem with the code. An extra `,` in:

    browserSyncInit([path.join(conf.paths.tmp, '/serve'), conf.paths.src, , 'bower_components/font-awesome']);
