### ISSUE TITLE
Not refreshing the browser!

### ISSUE THREAD

**Issue by rajinder-yadav** [BrowserSync/browser-sync#1276]
### Issue details
I have a markdown file that I change and convert to html using pandoc.
browsersync is detecting the file change but does not refresh the browser.
I am running it on Linux 4.4.0-57-generic.

Here is how I am running browsersync:

```bash
pandoc-markdown-to-html: $ browser-sync start --server './' --files '*.html' --index 'readme.html'
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3002
    External: http://192.168.0.10:3002
 -------------------------------------
          UI: http://localhost:3003
 UI External: http://192.168.0.10:3003
 -------------------------------------
[BS] Serving files from: ./
[BS] Watching files...
[BS] File changed: readme.html
```

_Please provide issue details here_.
Browser files to update, I need to manually refresh the browser to see the changes.

### Steps to reproduce/test case

_Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies)_.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.18.5   ]
- Node        [7.2.1    ]
- Npm         [4.0.3    ]

### Affected platforms

- [ 4.4.0-57-generic.] linux

### Browsersync use-case

- [x] CLI

### If CLI, please paste the entire command below

`browser-sync start --server './' --files '*.html' --index 'readme.html'`

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

**Comment by mazer-rakham** [comment]
I am getting the same issue, but I can see an error in mine, args.db is not a function 
`[BS] Reloading Browsers...
[14:08:30] Starting 'php'...
[14:08:30] Finished 'php' after 5.72 ms
[14:08:30] Starting 'sass'...
[BS] 1 file changed (main_stylesheet.css)
[14:08:30] Finished 'sass' after 11 ms
[14:08:30] Starting 'browser-sync'...
[14:08:30] 'browser-sync' errored after 241 μs
[14:08:30] TypeError: args.cb is not a function
    at Object.init (C:\Users\Administrator\Desktop\sideways_gradum\node_modules\browser-sync\lib\public\init.js:25:25)
    at Gulp.<anonymous> (C:\Users\Administrator\Desktop\sideways_gradum\gulpfile.js:23:17)
    at module.exports (C:\Users\Administrator\Desktop\sideways_gradum\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\Administrator\Desktop\sideways_gradum\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\Administrator\Desktop\sideways_gradum\node_modules\orchestrator\index.js:214:10)
    at C:\Users\Administrator\Desktop\sideways_gradum\node_modules\orchestrator\index.js:279:18
    at finish (C:\Users\Administrator\Desktop\sideways_gradum\node_modules\orchestrator\lib\runTask.js:21:8)
    at C:\Users\Administrator\Desktop\sideways_gradum\node_modules\orchestrator\lib\runTask.js:52:4
    at f (C:\Users\Administrator\Desktop\sideways_gradum\node_modules\once\once.js:17:25)
    at Transform.onend (C:\Users\Administrator\Desktop\sideways_gradum\node_modules\end-of-stream\index.js:31:18)
[BS] Reloading Browsers...
PHP 7.0.11 Development Server started at Thu Dec 29 14:08:30 2016
Listening on http://127.0.0.1:8010
Document root is C:\Users\Administrator\Desktop\sideways_gradum\app
Press Ctrl-C to quit.
[Thu Dec 29 14:08:31 2016] 127.0.0.1:49651 [200]: /
PHP 7.0.11 Development Server started at Thu Dec 29 14:08:31 2016
Listening on http://127.0.0.1:8010
Document root is C:\Users\Administrator\Desktop\sideways_gradum\app
Press Ctrl-C to quit.
[Thu Dec 29 14:08:31 2016] 127.0.0.1:49652 [200]: /`

**Comment by shakyShane** [comment]
@rajinder-yadav have you checked https://browsersync.io/docs#requirements?

do you see the 'Connected to Browsersync' message in the browser?

**Comment by rajinder-yadav** [comment]
@shakyShane I corrected the issue and told pandoc to create a proper html doc, I see the async tag getting injected.

However after 2 or 3 file changes, browsersync stop refreshing. I am back to manual refresh indefinitely.

Looking at devtools, network tab I see this when it stop syncing.

![bsync](https://cloud.githubusercontent.com/assets/439226/21717407/b1cddfe2-d3de-11e6-8a8a-4c2558f045ff.png)

**Comment by rajinder-yadav** [comment]
Looking at Browsersync UI, when it's first connect, no browser is listed? I've tired FF and Chrome set as default browser.

![bsui](https://cloud.githubusercontent.com/assets/439226/21717607/0f2dd15a-d3e0-11e6-8a3a-3e014e1a2de8.png)

**Comment by rajinder-yadav** [comment]
I've also used `dev-ip` and tried the "external ip" listed by this tool which is also shown in the browsersync UI, same issue.

**Comment by mazer-rakham** [comment]
Mine does not throw an error when I first run gulp app, it brings up the browser and everything fine, it is only when I save a file and it refreshes. But another weird thing, I have the exact same set up on another project, same gulpfile and everything, and it works fine on that project...

**Comment by mazer-rakham** [comment]
Ok, so brand new install on node v 4.6.0, is throwing the args error, but it is still refreshing the browsers....
