### ISSUE TITLE
browsersync + http2 + compression

### ISSUE THREAD

**Issue by Paul-frc** [BrowserSync/browser-sync#1443]
### Issue details

_Please provide issue details here_.

### Steps to reproduce/test case

_Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies)_.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.18.13]
- Node        [8.5]
- Npm         [5.4.2]

### Affected platforms

- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

Can't seem to get everything to play nicely

```javascript
var browserSync  = require('browser-sync');
var compression  = require('compression');
gulp.task('browser-sync', function() {
    browserSync.init({
        server: {
            baseDir: "dist",
            middleware: [compression()]
        },
        httpModule: 'http2',
        https: {
            key: "/Users/paulbrowne/.ssl/localhost.key",
            cert: "/Users/paulbrowne/.ssl/localhost.crt"
        }
    })
})
```
gives the error
```
Error: Can't set headers after they are sent.
    at OutgoingResponse.setHeader (/Users/paulbrowne/Documents/Projects/html5-gulp-boilerplate/node_modules/http2/lib/http.js:360:31)
    at OutgoingResponse.res.end (/Users/paulbrowne/Documents/Projects/html5-gulp-boilerplate/node_modules/resp-modifier/index.js:166:25)
    at OutgoingResponse.end (/Users/paulbrowne/Documents/Projects/html5-gulp-boilerplate/node_modules/compression/index.js:107:21)
    at ReadStream.onend (_stream_readable.js:598:10)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at ReadStream.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by Gijsjan** [comment]
I had the same issue with `proxy-middleware`. Can't set a header on a http2 response. Is compression() trying to set a header?
