### ISSUE TITLE
throw new TypeError('Path must be a string. Received ' +

### ISSUE THREAD

**Issue by aubreyzhou** [BrowserSync/browser-sync#1483]
### Issue details
When trying to run `browser-sync start --server --directory --files "*"`, I got this:`

```bash
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at posix.resolve (path.js:426:5)
    at /usr/local/lib/node_modules/browser-sync/dist/server/static-server.js:26:32
    at updateInDeepMap (/usr/local/lib/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1973:22)
    at updateInDeepMap (/usr/local/lib/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1982:23)
    at Map.updateIn (/usr/local/lib/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1280:26)
    at Map.update (/usr/local/lib/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1272:14)
    at createServer (/usr/local/lib/node_modules/browser-sync/dist/server/static-server.js:20:10)
    at createServer (/usr/local/lib/node_modules/browser-sync/dist/server/index.js:72:42)
    at module.exports.plugin (/usr/local/lib/node_modules/browser-sync/dist/server/index.js:12:20)

```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.23.2   ]
- Node        [  4.8.7  /  8.9.4]
- Npm         [  2.15.11  ]

### Affected platforms
- [ ] OS High Sierra

**Comment by andrericardo** [comment]
Another way to replicate this

[package.json.txt](https://github.com/BrowserSync/browser-sync/files/1604740/package.json.txt)

> mv package.json.txt package.json
> npm install
> npm start

```

> gum@1.0.0 start /Users/andre/workspace/JavaScript30/browser-sync
> browser-sync start --directory --server --files "*.css, *.html, *.js" --https

path.js:28
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at resolve (path.js:1179:7)
    at /Users/andre/workspace/JavaScript30/browser-sync/node_modules/browser-sync/dist/server/static-server.js:26:32
    at updateInDeepMap (/Users/andre/workspace/JavaScript30/browser-sync/node_modules/immutable/dist/immutable.js:1973:22)
    at updateInDeepMap (/Users/andre/workspace/JavaScript30/browser-sync/node_modules/immutable/dist/immutable.js:1982:23)
    at Map.updateIn (/Users/andre/workspace/JavaScript30/browser-sync/node_modules/immutable/dist/immutable.js:1280:26)
    at Map.update (/Users/andre/workspace/JavaScript30/browser-sync/node_modules/immutable/dist/immutable.js:1272:14)
    at createServer (/Users/andre/workspace/JavaScript30/browser-sync/node_modules/browser-sync/dist/server/static-server.js:20:10)
    at createServer (/Users/andre/workspace/JavaScript30/browser-sync/node_modules/browser-sync/dist/server/index.js:72:42)
    at module.exports.plugin (/Users/andre/workspace/JavaScript30/browser-sync/node_modules/browser-sync/dist/server/index.js:12:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gum@1.0.0 start: `browser-sync start --directory --server --files "*.css, *.html, *.js" --https`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gum@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andre/.npm/_logs/2018-01-04T21_20_49_741Z-debug.log

```

**Comment by shakyShane** [comment]
browser-sync@2.23.3
