### ISSUE TITLE
TypeError: Path must be a string. Received true

### ISSUE THREAD

**Issue by wzup** [BrowserSync/browser-sync#1522]
Why does it throw?
```
$ NODE_ENV=production ./node_modules/.bin/browser-sync start -ss 'dist'

path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received true
    at assertPath (path.js:28:11)
    at resolve (path.js:1181:7)
    at /home/user/app/client/node_modules/browser-sync/dist/server/static-server.js:39:37
    at Array.map (<anonymous>)
    at /home/user/app/client/node_modules/browser-sync/dist/server/static-server.js:34:35
    at updateInDeepMap (/home/user/app/client/node_modules/immutable/dist/immutable.js:1971:22)
    at updateInDeepMap (/home/user/app/client/node_modules/immutable/dist/immutable.js:1980:23)
    at Map.updateIn (/home/user/app/client/node_modules/immutable/dist/immutable.js:1278:26)
    at Map.update (/home/user/app/client/node_modules/immutable/dist/immutable.js:1270:14)
    at createServer (/home/user/app/client/node_modules/browser-sync/dist/server/static-server.js:33:10)
```

**Comment by wzup** [comment]
6 days

**Comment by shakyShane** [comment]
```diff
-NODE_ENV=production ./node_modules/.bin/browser-sync start -ss 'dist'
+NODE_ENV=production ./node_modules/.bin/browser-sync start -s 'dist'
```

or, if you're on the latest version, simply`

```bash
+NODE_ENV=production ./node_modules/.bin/browser-sync dist
```
