### ISSUE TITLE
Latest version on npm don't have index file

### ISSUE THREAD

**Issue by 7iomka** [BrowserSync/browser-sync#1549]
### Issue details
Error: ENOENT: no such file or directory,  ........ node_modules\browser-sync\client\dist\index.min.js

**Comment by vinceshere** [comment]
Same problem here... Reload/Stream functions suddenly stopped work.

**Comment by darkzairen** [comment]
Same issue here, after updating to v2.24.0

**Comment by huijing** [comment]
Same issue. Error log as follows:
```
Error: ENOENT: no such file or directory, open '/Users/.../node_modules/browser-sync/client/dist/index.min.js'
    at Object.fs.openSync (fs.js:545:3)
    at Object.fs.readFileSync (fs.js:451:33)
    at /Users/.../node_modules/browser-sync/dist/snippet.js:87:29
    at /Users/.../node_modules/browser-sync/dist/client.js:52:35
    at Array.reduce (<anonymous>)
    at processItems (/Users/.../node_modules/browser-sync/dist/client.js:47:10)
    at /Users/.../node_modules/browser-sync/dist/client.js:80:22
    at call (/Users/.../node_modules/connect/index.js:239:7)
    at next (/Users/.../node_modules/connect/index.js:183:5)
    at next (/Users/.../node_modules/connect/index.js:161:14)
```

**Comment by Carlosdvp** [comment]
I began to see this error message after upgrading **npm** to **v6.0.0**; even with **browsersync v2.18.15**

**Comment by vinceshere** [comment]
But @Carlosdvp , if you check the Git histpry it was removed in one of the last commits:

https://github.com/BrowserSync/browser-sync/tree/master/client/dist

**Comment by Carlosdvp** [comment]
You are right @vinceshere I was looking through the node_modules for previous projects that I had been using browsersync with, and they were working fine because the contents for thar folder were intact. The cause as far as I can tell is that the contents for the directory you mention are now gone.

**Comment by inspector71** [comment]
Please change this issue's title to something like:

"index.min.js is missing from the latest version"

Not trying to be a grammar nasty but at least it would be easier to understand if it were "does not" instead of "don't".

**Comment by dhffdh** [comment]
OMG =(((

**Comment by dhffdh** [comment]
HEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEELP!!!)))))

**Comment by huochunpeng** [comment]
@dhffdh pin your version to the old one `"browser-sync": "2.23.7",`.

**Comment by dhffdh** [comment]
@huochunpeng THANK YOU =)

**Comment by shakyShane** [comment]
Thanks all for the fast feedback :)

I had removed the compiled assets from the repo, with the aim of rebuilding them only when publishing - but I used an incorrect NPM lifecycle hook - oops!

It's fixed now though browser-sync@2.24.1

❤️

**Comment by huochunpeng** [comment]
@shakyShane I like the removal in general.

FYI, but it could create some trouble for some users (like contributors) who directly installs the package from git repo, if they use yarn or pnpm.

https://github.com/yarnpkg/yarn/issues/5235
https://github.com/pnpm/pnpm/issues/855

**Comment by wasong** [comment]
@shakyShane Hi, I think this issue might be revived again from the latest release v2.27.10. I ras running v2.27.9 in my projects and started to get this error recently.

**Comment by gerbsen** [comment]
Same here in my new jHipster project with "browser-sync": "2.27.9",

**Comment by krmahadevan** [comment]
I also experienced the same issue when using JHipster to create a new standalone app using `browser-sync` version `2.27.9`. For now I have went back to pinning to an older version in the `package.json`viz., `"browser-sync": "2.24.1"`

**Comment by AdrienPoupa** [comment]
I can confirm that the latest 2.27.10 triggers this error, reverting to 2.27.9 fixes it.

**Comment by Malak88** [comment]
In jhipster, instead of browser-sync-client@2.27.10 change it to browser-sync-client@2.27.9 by

1. Delete package-lock.json 
2. install **npm i browser-sync-client@2.27.9**
3. npm install
4. check  package.json to verify  the update of  **browser-sync-client**  then try **./mvnw** or  **npm start**

**Comment by djphan** [comment]
I ran into this issue testing out a browser sync update. Since this issue was closed back 2018 and fixed does it make sense to reopen this thread or make a new one since a recent update in client caused the same issue?

Currently my workaround is to keep my pinned package.lock file for browser sync to the older version.

**Comment by mimkorn** [comment]
Same issue still at 2.26.13

**Comment by toFrankie** [comment]
+1

- browser-sync v2.27.7
- node v16.20.0
- pnpm v8.5.0

```shell
→ ●● svg $ pnpm start                                                                                                                                                                             [17:28:57]

> svg@1.0.0 start /Users/frankie/Web/ifanr/wechat-svg-post/svg
> gulp start

[17:29:12] Using gulpfile ~/Web/ifanr/wechat-svg-post/svg/gulpfile.js
[17:29:12] Starting 'start'...
[Browsersync] Access URLs:
 ---------------------------------
    Local: http://localhost:3000
 External: http://172.16.3.83:3000
 ---------------------------------
[Browsersync] Serving files from: dist-dev/pages
Error: Cannot find module 'browser-sync-client/dist/index.min.js'
Require stack:
- /Users/frankie/Web/ifanr/wechat-svg-post/svg/node_modules/.pnpm/browser-sync@2.27.7/node_modules/browser-sync/dist/snippet.js
- /Users/frankie/Web/ifanr/wechat-svg-post/svg/node_modules/.pnpm/browser-sync@2.27.7/node_modules/browser-sync/dist/hooks.js
- /Users/frankie/Web/ifanr/wechat-svg-post/svg/node_modules/.pnpm/browser-sync@2.27.7/node_modules/browser-sync/dist/browser-sync.js
- /Users/frankie/Web/ifanr/wechat-svg-post/svg/node_modules/.pnpm/browser-sync@2.27.7/node_modules/browser-sync/dist/index.js
- /Users/frankie/Web/ifanr/wechat-svg-post/svg/gulpfile.js
- /Users/frankie/Web/ifanr/wechat-svg-post/svg/node_modules/.pnpm/gulp-cli@2.3.0/node_modules/gulp-cli/lib/shared/require-or-import.js
- /Users/frankie/Web/ifanr/wechat-svg-post/svg/node_modules/.pnpm/gulp-cli@2.3.0/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js
- /Users/frankie/Web/ifanr/wechat-svg-post/svg/node_modules/.pnpm/gulp-cli@2.3.0/node_modules/gulp-cli/index.js
- /Users/frankie/Web/ifanr/wechat-svg-post/svg/node_modules/.pnpm/gulp@4.0.2/node_modules/gulp/bin/gulp.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.resolve (node:internal/modules/cjs/helpers:114:19)
    at /Users/frankie/Web/ifanr/wechat-svg-post/svg/node_modules/.pnpm/browser-sync@2.27.7/node_modules/browser-sync/dist/snippet.js:87:50
    at /Users/frankie/Web/ifanr/wechat-svg-post/svg/node_modules/.pnpm/browser-sync-client@2.29.1/node_modules/browser-sync-client/index.js:59:39
    at Array.reduce (<anonymous>)
    at processItems (/Users/frankie/Web/ifanr/wechat-svg-post/svg/node_modules/.pnpm/browser-sync-client@2.29.1/node_modules/browser-sync-client/index.js:54:10)
    at /Users/frankie/Web/ifanr/wechat-svg-post/svg/node_modules/.pnpm/browser-sync-client@2.29.1/node_modules/browser-sync-client/index.js:89:22
    at call (/Users/frankie/Web/ifanr/wechat-svg-post/svg/node_modules/.pnpm/connect@3.6.6/node_modules/connect/index.js:239:7)
    at next (/Users/frankie/Web/ifanr/wechat-svg-post/svg/node_modules/.pnpm/connect@3.6.6/node_modules/connect/index.js:183:5)
    at next (/Users/frankie/Web/ifanr/wechat-svg-post/svg/node_modules/.pnpm/connect@3.6.6/node_modules/connect/index.js:161:14)
```

However, it seems to be working fine with `yarn`, which is strange!
