### ISSUE TITLE
Task function must be specified

### ISSUE THREAD

**Issue by pinty** [BrowserSync/browser-sync#1619]
### Issue details

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\X\X\X\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\X\X\X\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (C:\X\X\X\gulpfile.js:21:6)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)

### Steps to reproduce/test case

I just copy-paste the code from your documentation, and it does not work at all.
Neither by making the core runnable, it does not refresh the browser when it should.
gulpfile -> https://gist.github.com/pinty/f511dcbf1fb8aef38b47a6524cf63634

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.26.0]
- Node        [10]
- Npm         [6.4.1]

### Affected platforms

- [ ] linux
- [x] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

**Comment by shakyShane** [comment]
@pinty that's because you're trying to use Gulp 4 features (like gulp.parallel('serve')) and the task definition of `serve` is incorrect, see https://codeburst.io/switching-to-gulp-4-0-271ae63530c0 and https://fettblog.eu/gulp-4-parallel-and-series/
