### ISSUE TITLE
Error: listen EACCES: permission denied 0.0.0.0:3100

### ISSUE THREAD

**Issue by Chriscon1994** [BrowserSync/browser-sync#1705]
Node.js: v12.4.0.
Windows: 10
NPM: 6.9.0

I keep getting this error and I'm unsure how to resolve it. Any help would be greatly appreciated, error code below:

events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:3100
    at Server.setupListenHandle [as _listen2] (net.js:1209:19)
    at listenInCluster (net.js:1274:12)
    at Server.listen (net.js:1362:7)
    at Object.<anonymous> (C:\Users\chrisconnolly\customer-support\server.js:167:8)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
Emitted 'error' event at:
    at emitErrorNT (net.js:1253:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 3100

**Comment by valadas** [comment]
possible duplicate of #1668 , I just had this issue and it was caused by a virtual network card.
On windows, I went to Control Panel -> Network Connections and disabled all virtual network interfaces like Fortinet, Hyper-V, Avast VPN, TeamViewer VPN and more, I had many virtual interfaces.

If you cannot disable them all then disable them one by one until you find the culprit and decide what to do from there...

**Comment by Bensigo** [comment]
You use Sudo if using UNIX .

**Comment by AustEcon** [comment]
The only thing that fixed this for me (after disabling all but my main network adapter) was to follow the guidelines at the bottom of this article here:
https://www.windowscentral.com/how-regain-internet-access-after-installing-update-windows-10

For a full network reset! Worked immediately on reboot (I have docker for windows and had recently messed about with both switching to windows containers and then back to linux condainers + Android virtual machine stuff that needed Hyper-V turned back on...)... Must have played havoc with network adapters...

So the nuclear option: Full network reset 😉

**Comment by magictomagic** [comment]
run this .bat file
```bat
%1 mshta vbscript:CreateObject("Shell.Application").ShellExecute("cmd.exe","/c %~s0 ::","","runas",1)(window.close)&&exit
cd /d "%~dp0"
net stop winnat
net start winnat
exit
```

**Comment by halfway-there1** [comment]
I was facing somewhat same issue for most of ports (even on ports above 1024 that don't need any special permission)
This helped me on **#Windows**

```
net stop winnat
net start winnat
```

**Comment by seyyed-sina** [comment]
> run this .bat file
> 
> %1 mshta vbscript:CreateObject("Shell.Application").ShellExecute("cmd.exe","/c %~s0 ::","","runas",1)(window.close)&&exit
> cd /d "%~dp0"
> net stop winnat
> net start winnat
> exit

Perfectly worked for me!
