### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::3000

### ISSUE THREAD

**Issue by jeffschwartz** [BrowserSync/browser-sync#1873]
### Issue details

Trio is a node-based static site generator that integrates BrowserSync into its tool chain. Trio is meant to be installed globally so users don't have to install Trio into each static site project that they are developing. I am now preparing the next release of Trio which changes how it uses BrowserSync from previous versions.

In previous versions Trio directly calls bs.reload when notified that files in the user's project have changed resulting in Trio generating the related static site assets and therefore needing the browser to refresh the page.

In the next release Trio no longer directly calls any BrowserSync api methods and instead relies on using bs.watch(files, cb):

```js
"use strict";
const { sep } = require("path");
const bsf = require("browser-sync");
const { targetFolder } = require("../config");

module.exports = () => {
    const bs = bsf.create();
    const baseUrl = process.env.TRIO_ENV_baseUrl;

    bs.watch(`.${sep}${targetFolder}${sep}**${sep}*.*`, (event, file) => {
        bs.reload(file);
    });

    bs.init({
        server: {
            baseDir: `.${sep}${targetFolder}`,
            middleware: (req, res, next) => {
                if (baseUrl && baseUrl.length > 0) {
                    const url = req.url.slice(baseUrl.length);
                    req.url = url.length === 0 ? sep : url;
                }
                return next();
            }
        },
        notify: false
    });

    bs.watch(`.${sep}${targetFolder}${sep}**${sep}*.*`, (event, file) => {
        bs.reload(file);
    });
};
```
The issue I am reporting is that in the current version of Trio I am able to have more than one instance of Trio running concurrently and BrowserSync would auto increment the port number to be something greater than 3000. In the next release version of Trio when attempting to run more than one instance of Trio concurrently BrowserSync throws the following stack trace:

```shell
Starting chokidar
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at module.exports.plugin (/Users/Jeff/Development/trio/node_modules/browser-sync/dist/server/index.js:27:25)
    at Object.startServer [as fn] (/Users/Jeff/Development/trio/node_modules/browser-sync/dist/async.js:177:52)
    at /Users/Jeff/Development/trio/node_modules/browser-sync/dist/browser-sync.js:120:14
    at iterate (/Users/Jeff/Development/trio/node_modules/browser-sync/dist/utils.js:268:9)
    at /Users/Jeff/Development/trio/node_modules/browser-sync/dist/utils.js:279:21
    at executeTask (/Users/Jeff/Development/trio/node_modules/browser-sync/dist/browser-sync.js:136:13)
    at Object.mergeMiddlewares [as fn] (/Users/Jeff/Development/trio/node_modules/browser-sync/dist/async.js:166:9)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 3000
}
```
### Steps to reproduce/test case

Run 2 instances of Trio concurrently.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.26.14]
- Node        [14.16.1]
- Npm         [6.14.12]

### Affected platforms

- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [x] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

```js
"use strict";
const { sep } = require("path");
const bsf = require("browser-sync");
const { targetFolder } = require("../config");

module.exports = () => {
    const bs = bsf.create();
    const baseUrl = process.env.TRIO_ENV_baseUrl;

    bs.watch(`.${sep}${targetFolder}${sep}**${sep}*.*`, (event, file) => {
        bs.reload(file);
    });

    bs.init({
        server: {
            baseDir: `.${sep}${targetFolder}`,
            middleware: (req, res, next) => {
                if (baseUrl && baseUrl.length > 0) {
                    const url = req.url.slice(baseUrl.length);
                    req.url = url.length === 0 ? sep : url;
                }
                return next();
            }
        },
        notify: false
    });

    bs.watch(`.${sep}${targetFolder}${sep}**${sep}*.*`, (event, file) => {
        bs.reload(file);
    });
};
```

**Comment by jeffschwartz** [comment]
So I got this to work by calling portscanner.findAPortNotInUse as per below:

```javascript
"use strict";
const { sep } = require("path");
const bsf = require("browser-sync");
const { findAPortNotInUse } = require("portscanner"); // <-- ?
const { targetFolder } = require("../config");

module.exports = async () => {
    const bs = bsf.create();
    const baseUrl = process.env.TRIO_ENV_baseUrl;

    bs.watch(`.${sep}${targetFolder}${sep}**${sep}*.*`, (event, file) => {
        bs.reload(file);
    });

    bs.init({
        server: {
            baseDir: `.${sep}${targetFolder}`,
            middleware: (req, res, next) => {
                if (baseUrl && baseUrl.length > 0) {
                    const url = req.url.slice(baseUrl.length);
                    req.url = url.length === 0 ? sep : url;
                }
                return next();
            }
        },
        notify: false,
        port: await findAPortNotInUse(3000) // <-- ?
    });
};
```
Is this now the way to auto increment the port (meaning the user must implement it as I have) or shouldn't BrowserSync do this by default if port number is not provided via bs.init?
