### ISSUE TITLE
BROWSERSYNC FAIL TO INSTALL

### ISSUE THREAD

**Issue by tanyaptz** [BrowserSync/browser-sync#1963]
### Issue details

_Please provide issue details here_.

### Steps to reproduce/test case

_Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies)_.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [    ]
- Node        [    ]
- Npm         [    ]

### Affected platforms

- [ ] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

**Comment by edwmurph** [comment]
<details>
<summary>not sure if this is related to the OP's issue, but when i `npm i` and run my app locally, now i get this error:</summary>

```
Error: Cannot find module 'browser-sync-client/dist/index.min.js'
Require stack:
- /Users/emurphy/code/starry/banshee/node_modules/browser-sync/dist/snippet.js
- /Users/emurphy/code/starry/banshee/node_modules/browser-sync/dist/hooks.js
- /Users/emurphy/code/starry/banshee/node_modules/browser-sync/dist/browser-sync.js
- /Users/emurphy/code/starry/banshee/node_modules/browser-sync/dist/index.js
- /Users/emurphy/code/starry/banshee/scripts/nodemon.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at /Users/emurphy/code/starry/banshee/node_modules/browser-sync/dist/snippet.js:87:52
    at /Users/emurphy/code/starry/banshee/node_modules/browser-sync-client/index.js:59:39
    at Array.reduce (<anonymous>)
    at processItems (/Users/emurphy/code/starry/banshee/node_modules/browser-sync-client/index.js:54:10)
    at /Users/emurphy/code/starry/banshee/node_modules/browser-sync-client/index.js:89:22
    at call (/Users/emurphy/code/starry/banshee/node_modules/connect/index.js:239:7)
    at next (/Users/emurphy/code/starry/banshee/node_modules/connect/index.js:183:5)
    at next (/Users/emurphy/code/starry/banshee/node_modules/connect/index.js:161:14)
```
</details>

pinning `browser-sync-client` to `2.27.9` in my package.json seems to fix the error

the error is caused by the `index.min.js` file not existing which i confirmed in my node_modules

seemingly this was introduced in [this commit](https://github.com/BrowserSync/browser-sync/commit/f6965a67277bdadfaa4943e7b90e4ed6a71e90af)
