### ISSUE TITLE
browser-sync throwing 'task completion callback called too many times'

### ISSUE THREAD

**Issue by kumavis** [BrowserSync/browser-sync#421]
```js
gulp.task('browser-sync', browserSync)
function browserSync() {
  browserSync({
    // logSnippet: false,
    server: {
      baseDir: './dist',
    },
    // port: process.env.PORT || 3000,
  })
}
```
```
╭─{👘 } kumavis in ~/Development/Node/vapor on (master✱)
╰─○ gulp browser-sync
[15:10:46] Using gulpfile ~/Development/Node/vapor/gulpfile.js
[15:10:46] Starting 'browser-sync'...
[15:10:46] Finished 'browser-sync' after 15 ms
[BS] Copy the following snippet into your website, just before the closing </body> tag
<script type='text/javascript' id="__bs_script__">//<![CDATA[
    document.write("<script async src='//HOST:3000/browser-sync/browser-sync-client.2.0.0-rc5.js'><\/script>".replace(/HOST/g, location.hostname).replace(/PORT/g, location.port));
//]]></script>
[15:10:46] 'browser-sync' errored after 143 ms
[15:10:46] Error: task completion callback called too many times
    at finish (/Users/kumavis/Development/Node/vapor/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:17:10)
    at cb (/Users/kumavis/Development/Node/vapor/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:31:3)
    at /Users/kumavis/Development/Node/vapor/node_modules/browser-sync/lib/browser-sync.js:243:12
    at /Users/kumavis/Development/Node/vapor/node_modules/browser-sync/node_modules/async-each-series/index.js:15:40
    at executeTask (/Users/kumavis/Development/Node/vapor/node_modules/browser-sync/lib/browser-sync.js:171:13)
    at Object.module.exports.initUserPlugins [as fn] (/Users/kumavis/Development/Node/vapor/node_modules/browser-sync/lib/async.js:234:9)
    at /Users/kumavis/Development/Node/vapor/node_modules/browser-sync/lib/browser-sync.js:126:14
    at iterate (/Users/kumavis/Development/Node/vapor/node_modules/browser-sync/node_modules/async-each-series/index.js:8:5)
    at /Users/kumavis/Development/Node/vapor/node_modules/browser-sync/node_modules/async-each-series/index.js:16:16
    at executeTask (/Users/kumavis/Development/Node/vapor/node_modules/browser-sync/lib/browser-sync.js:171:13)
^C%                                                                                                                                                                                 

╭─{👘 } kumavis in ~/Development/Node/vapor on (master✱)
╰─○ npm ls | grep browser-sync
├─┬ browser-sync@2.0.0-rc5
│ ├── browser-sync-client@1.0.1
│ ├─┬ browser-sync-ui@0.4.4
npm ERR! extraneous: gulp-rimraf@0.1.1 /Users/kumavis/Development/Node/vapor/node_modules/gulp-rimraf
npm ERR! extraneous: esprima@1.1.0-dev /Users/kumavis/Development/Node/vapor/node_modules/brfs/node_modules/static-module/node_modules/falafel/node_modules/esprima
npm ERR! extraneous: gulp-clean@0.3.1 /Users/kumavis/Development/Node/vapor/node_modules/gulp-clean
npm ERR! not ok code 0
```

**Comment by kumavis** [comment]
been banging my head on this for a few hours, not sure whats going on.

**Comment by shinnn** [comment]
It's not an issue for browser-sync.

Read this. https://github.com/gulpjs/gulp/issues/813#issuecomment-66891609

**Comment by shakyShane** [comment]
as @shinnn says, this is not an issue with BrowserSync, but rather how you're using Gulp.

We'd still be happy to help, but you need to provide your entire `gulpfile.js` - we cannot debug your problem from a snippet.

**Comment by shinnn** [comment]
@kumavis The simplest way to fix the problem is renaming the task function from `browserSync`.

```js
gulp.task('browser-sync', serve)
function serve() { // !!!!!!!!! Do not use the name `browserSync` here !!!!!!!!!
  browserSync({
    // logSnippet: false,
    server: {
      baseDir: './dist',
    },
    // port: process.env.PORT || 3000,
  })
}
```

**Comment by kumavis** [comment]
ohhhhhh how did I not see that. well i feel like an idiot now. thanks all!
```js
function browserSync() {
  browserSync({
```

**Comment by shinnn** [comment]
@kumavis No problem!

**Comment by shakyShane** [comment]
:smile:
