### ISSUE TITLE
Passing options into server causes an error

### ISSUE THREAD

**Issue by pspeter3** [BrowserSync/browser-sync#424]
```
[14:02:21] TypeError: Object [object Object] has no method 'get'
    at Object.opts.callbacks.server (node_modules/browser-sync/lib/cli/cli-options.js:84:27)
    at node_modules/browser-sync/lib/cli/cli-options.js:282:54
    at node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1139:46
    at node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1872:16
    at ValueNode.iterate (node_modules/browser-sync/node_modules/immutable/dist/immutable.js:2239:12)
    at BitmapIndexedNode.iterate.HashArrayMapNode.iterate (node_modules/browser-sync/node_modules/immutable/dist/immutable.js:2232:24)
    at HashArrayMapNode.BitmapIndexedNode.iterate.HashArrayMapNode.iterate (node_modules/browser-sync/node_modules/immutable/dist/immutable.js:2232:24)
    at Map.__iterate (node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1870:32)
    at KeyedIterable.mappedSequence.__iterateUncached (node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1138:23)
    at seqIterate (node_modules/browser-sync/node_modules/immutable/dist/immutable.js:601:16)
```

**Comment by shakyShane** [comment]
Which version?
Which platform are you running on?
What configuration did you use?

https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md

**Comment by pspeter3** [comment]
Sorry

Version: 2.0.0-rc6
Platform: Os X
Configuration:

```ts
        server: {
            baseDir: "_build",
            routes: {
                "/mocha.js": "node_modules/gulp-mocha/node_modules/mocha/mocha.js"
            }
        }
```

**Comment by shakyShane** [comment]
You have an error in your syntax.

It should be 

```js
server: {
    baseDir: "_build",
    routes: {
        "/mocha.js": "node_modules/gulp-mocha/node_modules/mocha/mocha.js"
    }
}
```

This use-case is covered in the test suite.
https://github.com/BrowserSync/browser-sync/blob/master/test/specs/e2e/server/e2e.server.routes.js#L16-L25
