### ISSUE TITLE
Ngrok is failing npm install of browser-sync

### ISSUE THREAD

**Issue by softEngJason** [BrowserSync/browser-sync#429]
I see that a new commit was done against Ngrok, in the last 24 hours.  We are getting the following on npm install of browser-sync:

```bash
sync/node_modules/ngrok
> node ./postinstall.js

ngrok - Downloading newest binary...
-
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)

npm ERR! ngrok@0.1.98 postinstall: `node ./postinstall.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the ngrok@0.1.98 postinstall script.
npm ERR! This is most likely a problem with the ngrok package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ngrok
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "i"
npm ERR! cwd /Applications/MAMP/htdocs/kit/slides/node_modules/browser-sync
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

Can you help?

**Comment by softEngJason** [comment]
Thanks shaky!!
