### ISSUE TITLE
TypeError: Cannot call method 'map' of null

### ISSUE THREAD

**Issue by adammockor** [BrowserSync/browser-sync#440]
Hello,

after upgrading form 1.9.1 -> 2.0.1 I got error in CLI.

```bash
[16:49:10] TypeError: Cannot call method 'map' of null
    at Object.opts.callbacks.files (/Users/adam/Praca/temp/1.2.0/node_modules/browser-sync/lib/cli/cli-options.js:273:40)
    at /Users/adam/Praca/temp/1.2.0/node_modules/browser-sync/lib/cli/cli-options.js:292:54
    at /Users/adam/Praca/temp/1.2.0/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1139:46
    at /Users/adam/Praca/temp/1.2.0/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1872:16
    at ValueNode.iterate (/Users/adam/Praca/temp/1.2.0/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:2239:12)
    at BitmapIndexedNode.iterate.HashArrayMapNode.iterate (/Users/adam/Praca/temp/1.2.0/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:2232:24)
    at HashArrayMapNode.BitmapIndexedNode.iterate.HashArrayMapNode.iterate (/Users/adam/Praca/temp/1.2.0/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:2232:24)
    at Map.__iterate (/Users/adam/Praca/temp/1.2.0/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1870:32)
    at KeyedIterable.mappedSequence.__iterateUncached (/Users/adam/Praca/temp/1.2.0/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1138:23)
    at seqIterate (/Users/adam/Praca/temp/1.2.0/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:601:16)
    at KeyedIterable.Seq.__iterate (/Users/adam/Praca/temp/1.2.0/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:261:14)
    at KeyedIterable.mixin.forEach (/Users/adam/Praca/temp/1.2.0/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:4265:19)
    at /Users/adam/Praca/temp/1.2.0/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1740:16
    at Map.withMutations (/Users/adam/Praca/temp/1.2.0/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1848:7)
    at new Map (/Users/adam/Praca/temp/1.2.0/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1737:20)
    at reify (/Users/adam/Praca/temp/1.2.0/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1673:37)
```
Setup:
```js
gulp.task('browser-sync', function() {
  browserSync.init(null, {
    server: {
      baseDir: ['app', '.tmp'],
      routes: {
        '/bower_components': 'bower_components'
      }
    },
    notify: false,
    debugInfo: false,
    host: 'localhost'
  });
});
```
OS: OS X 10.10
Node.js: 10.30

Did I miss something?

**Comment by shakyShane** [comment]
try this

```js
gulp.task('browser-sync', function() {
  browserSync({
    server: {
      baseDir: ['app', '.tmp'],
      routes: {
        '/bower_components': 'bower_components'
      }
    },
    notify: false,
    debugInfo: false,
    host: 'localhost'
  });
});
```

**Comment by adammockor** [comment]
Thank you. I really missed that.
