### ISSUE TITLE
TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by hydrotik** [BrowserSync/browser-sync#487]
Mac 10.9.5
Safari 7.1.3

I am trying to run a nodemon controlled instance and use browser sync to control the reload, etc. (I'm assuming this is using the proxy feature, but not 100% sure). I have commented out a previous livereload task, so disregard that.

```javascript
gulp.task('server', ['nodemon'], function () {

    browserSync.init(null, {
        proxy: "http://127.0.0.1:3000"
    });

    // Start Livereload
    //livereload.listen();

    // Restart when files change 
    // Markup
    gulp.watch(['./views/**/*.hbs'], ['livereload']);
    // Styles
    gulp.watch(['./scss/**/*.scss'], ['sass', 'sassdoc']);
    gulp.watch(['./public/stylesheets/**/*.css'], ['livereload']);
    // Javascript
    gulp.watch(['./public/javascripts/**/*.js', '!./public/javascripts/build/**/*.js'], ['jshint', 'scripts', 'livereload']);
    // Assets
    gulp.watch(['./public/images/**/*'], ['livereload']);

});

gulp.task('nodemon', function() {
  nodemon({
        script: './bin/www',
        ignore: ['./public/javascripts/']
      })
      //.on('change', ['lint'])
      .on('restart', function () {
        console.log('restarted!');
        //livereload.reload();
      });
});
```

I get the error:
```
[10:58:18] Starting 'browser-sync'...
[10:58:18] 'browser-sync' errored after 24 ms
[10:58:18] TypeError: Cannot read property 'map' of null
    at Object.opts.callbacks.files (/Users/dadams/Desktop/Node/dsgstyleguide/node_modules/browser-sync/lib/cli/cli-options.js:285:39)
    at /Users/dadams/Desktop/Node/dsgstyleguide/node_modules/browser-sync/lib/cli/cli-options.js:304:54
    at /Users/dadams/Desktop/Node/dsgstyleguide/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1139:46
    at /Users/dadams/Desktop/Node/dsgstyleguide/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1872:16
    at ValueNode.iterate (/Users/dadams/Desktop/Node/dsgstyleguide/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:2239:12)
    at BitmapIndexedNode.iterate.HashArrayMapNode.iterate [as iterate] (/Users/dadams/Desktop/Node/dsgstyleguide/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:2232:24)
    at HashArrayMapNode.BitmapIndexedNode.iterate.HashArrayMapNode.iterate [as iterate] (/Users/dadams/Desktop/Node/dsgstyleguide/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:2232:24)
    at Map.__iterate (/Users/dadams/Desktop/Node/dsgstyleguide/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1870:32)
    at KeyedIterable.mappedSequence.__iterateUncached (/Users/dadams/Desktop/Node/dsgstyleguide/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1138:23)
    at seqIterate (/Users/dadams/Desktop/Node/dsgstyleguide/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:601:16)
```

**Comment by hydrotik** [comment]
I've also found this https://github.com/BrowserSync/browser-sync/issues/440 but seems to be a slightly different use case having this work with nodemon.

**Comment by hydrotik** [comment]
When I do:
```javascript
browserSync.init({
      notify: false,
      debugInfo: false,
      proxy: "http://127.0.0.1:3000"
    });
```
I don't get the map error, but then I get a message saying the port is in use and another error:
```
[13:23:18] Using gulpfile ~/Desktop/Node/dsgstyleguide/gulpfile.js
[13:23:18] Starting 'scripts'...
[13:23:18] Finished 'scripts' after 8.36 ms
[13:23:18] Starting 'nodemon'...
[13:23:18] Finished 'nodemon' after 1.48 ms
[13:23:18] Starting 'server'...
[13:23:18] Finished 'server' after 93 ms
[13:23:18] Starting 'default'...
[13:23:18] Finished 'default' after 5.35 μs
[gulp] [nodemon] v1.3.7
[gulp] [nodemon] to restart at any time, enter `rs`
[gulp] [nodemon] watching: *.*
[gulp] [nodemon] starting `node ./bin/www`
[BS] Proxying: http://127.0.0.1:3000
[BS] Access URLs:
 ------------------------------------
       Local: http://localhost:3000
    External: http://10.34.6.193:3000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://10.34.6.193:3001
 ------------------------------------
Port 3000 is already in use
[gulp] [nodemon] app crashed - waiting for file changes before starting...
child_process.js:781
  child.stdout.addListener('data', function(chunk) {
              ^
TypeError: Cannot read property 'addListener' of undefined
    at Object.exports.execFile (child_process.js:781:15)
    at exports.exec (child_process.js:642:18)
    at changeFunction (/Users/dadams/Desktop/Node/dsgstyleguide/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:93:7)
    at module.exports [as _onTimeout] (/Users/dadams/Desktop/Node/dsgstyleguide/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:289:5)
    at Timer.listOnTimeout (timers.js:110:15)
```

I'm going to try and do it without nodemon

**Comment by hydrotik** [comment]
Got it working with:
```javascript
browserSync.init({
      notify: false,
      debugInfo: false,
      proxy: "http://127.0.0.1:3000",
      port: 9000
    });
```
Now on to getting the live reload to work!
