### ISSUE TITLE
[BS] [proxy error] connect ECONNREFUSED

### ISSUE THREAD

**Issue by thiagodebastos** [BrowserSync/browser-sync#527]
It seems that unless I manually add the snippet into html, I cannot connect to BS. I keep getting the connection refused error. Is this something related to my own settings? 
using debug I also see:
`[warn] Proxy address not reachable - is your server running?`
It is running because I can access it by running the same address from the browser.

**Comment by shakyShane** [comment]
Can we see your settings? What's your backend? 

https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md#-tips-for-a-creating-a-great-issue-report

**Comment by thiagodebastos** [comment]
Apologies for the late reply. I have been trying to explain this better and I was exhausted this morning. 

For some reason, I can get the proxy working by going through xip.io: `http://style.lifepluspizza.dev.192.168.1.85.xip.io`

however, `'http://style.lifepluspizza.dev'` still gives me the connection refused error.

These are my configs:
Server version: Apache/2.4.9 (Unix)


- - -

###  hosts
```hosts
127.0.0.1   localhost
255.255.255.255 broadcasthost
::1 localhost
fe80::1%lo0 localhost

# VHX START
127.0.0.1 style.lifepluspizza.dev
fe80::1%lo0 style.lifepluspizza.dev
```
- - -

### httpd.vhosts
```apache
NameVirtualHost *:80
<Directory "/Users/Thiago/Projects/lifepluspizza/patternlab/public/">
Allow From All
AllowOverride All
Options +Indexes
Require all granted
</Directory>
<VirtualHost *:80>
	ServerName "style.lifepluspizza.dev"
	ServerAlias "style.lifepluspizza.dev.*.*.*.*.xip.io"
	DocumentRoot "/Users/Thiago/Projects/lifepluspizza/patternlab/public"
</VirtualHost>
```
- - -

### gulpfile.js
https://gist.github.com/thiagodebastos/a01365df83e1f8edf32d
All I changed in the gulpfile was the server from `patternlab.dev` to `style.lifepluspizza.dev`.

### package.json
```json
{
  "name": "patternlab",
  "description": "patternlab project files",
  "version": "1.0.0",
  "devDependencies": {
    "axis": "^0.3.0",
    "browser-sync": "^2.3.1",
    "browserify": "^9.0.3",
    "del": "^1.1.1",
    "gulp": "^3.8.11",
    "gulp-autoprefixer": "2.1.0",
    "gulp-cache": "^0.2.8",
    "gulp-combine-media-queries": "0.2.0",
    "gulp-concat": "^2.5.2",
    "gulp-cssmin": "^0.1.6",
    "gulp-csso": "^1.0.0",
    "gulp-debug": "^2.0.1",
    "gulp-filter": "^2.0.2",
    "gulp-if": "^1.2.5",
    "gulp-imagemin": "^2.2.1",
    "gulp-jshint": "^1.9.4",
    "gulp-load-plugins": "^0.8.1",
    "gulp-notify": "^2.2.0",
    "gulp-replace": "^0.5.3",
    "gulp-size": "^1.2.1",
    "gulp-sourcemaps": "^1.5.1",
    "gulp-stylus": "^2.0.1",
    "gulp-uglify": "^1.1.0",
    "gulp-util": "^3.0.4",
    "jeet": "^6.1.2",
    "jshint-stylish-ex": "^0.2.0",
    "typographic": "^1.1.0"
  }
}
```

I've not run into this issue before and it has me quite confused!

**Comment by MattDiMu** [comment]
I've got the same issue when starting browser-sync as proxy from the commandline:

> browser-sync start --proxy="https://github.com" --logLevel=debug
=> 
> ...
> [warn] Proxy address not reachable - is your server running?
> [proxy error] connect ETIMEDOUT

It DOES work on a local server, however. So I assume it's some proxy setting? (I'm behind a corporate firewalll, but npm still works and may connect to github). 

I'm using Win7, npm@2.7.3, browser-sync@2.2.3.

**Comment by MattDiMu** [comment]
The issue still exists and from what logLevel=debug tells me, it makes no sense as browserSync seems to be able to access the site when checking its online-status...but when it should proxy it, it can't anymore:

```
browsersync start --proxy=www.google.com --logLevel=debug
```


```
....
[BS] [debug] -> Starting Step: Checking online status
[BS] [debug] Resolved www.google.com, setting online: true
[BS] [debug] Setting Option: online - true
[BS] [debug] +  Step Complete: Checking online status
...
...
[BS] [warn] Proxy address not reachable - is your server running?
[BS] [proxy error] connect ETIMEDOUT
[BS] [proxy error] connect ETIMEDOUT
```

**Comment by mvattuone** [comment]
Yep, I can confirm I am having this problem as well, though I am running it as a task in Gulp.

I'm running it via a PHP development server packaged with [WP-CLI](http://wp-cli.org) -- wish I could tell you more, but I don't really know anything about the underlying mechanics of it.

All of the initialization steps seemed to go through just fine.

**Comment by schiz** [comment]
I experience the same issue running browser sync as a watch task in gulp - during some time it works fine and livereloads the page as supposed to do, but at some point stops throwing this error in cli: 

Error: connection refused: localtunnel.me:43822 (check your firewall settings)
  at Socket.<anonymous>
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at emitErrorNT (net.js:1253:8)
  at doNTCallback2 (node.js:439:9)
  at process._tickCallback (node.js:353:17)
