### ISSUE TITLE
Error: browserSync.reload() of 2.6.0

### ISSUE THREAD

**Issue by htanjo** [BrowserSync/browser-sync#573]
I encountered a TypeError when using `browserSync.reload()` in my gulpfile.

The task works correctly with `browser-sync@2.5.3`, but it fails in `2.6.0`.
And when I comment out the line of `.pipe(reload({stream: true}))`, the task is completed.

I suppose the new `.reload()` method has an issue.

**My gulp task:**
```javascript
gulp.task('styles', function () {
  return gulp.src('app/assets/styles/main.scss')
    .pipe($.sourcemaps.init())
    .pipe($.sass({
      outputStyle: 'nested',
      precision: 10,
      includePaths: ['.'],
      onError: console.error.bind(console, 'Sass error:')
    }))
    .pipe($.postcss([
      require('autoprefixer-core')({browsers: ['last 1 version']})
    ]))
    .pipe($.sourcemaps.write())
    .pipe(gulp.dest('.tmp/assets/styles'))
    .pipe(reload({stream: true}));
});
```
[Whole gulpfile.js is here](https://github.com/rakuten-frontend/webpage-toolkit/blob/master/gulpfile.js).

**Error message:**
```
-> % gulp styles
[10:34:06] Using gulpfile ~/lab/webpage-toolkit/gulpfile.js
[10:34:06] Starting 'styles'...
[10:34:07] 'styles' errored after 357 ms
[10:34:07] TypeError: Cannot read property 'on' of undefined
    at DestroyableTransform.Stream.pipe (stream.js:65:7)
    at Gulp.<anonymous> (/Users/hiroyuki.tanjo/lab/webpage-toolkit/gulpfile.js:23:6)
    at module.exports (/Users/hiroyuki.tanjo/lab/webpage-toolkit/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/hiroyuki.tanjo/lab/webpage-toolkit/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/hiroyuki.tanjo/lab/webpage-toolkit/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/hiroyuki.tanjo/lab/webpage-toolkit/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/hiroyuki.tanjo/.nvm/versions/node/v0.12.0/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
stream.js:50
    if (dest.writable) {
            ^
TypeError: Cannot read property 'writable' of undefined
    at DestroyableTransform.ondata (stream.js:50:13)
    at DestroyableTransform.emit (events.js:107:17)
    at DestroyableTransform.<anonymous> (/Users/hiroyuki.tanjo/lab/webpage-toolkit/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:786:14)
    at DestroyableTransform.emit (events.js:104:17)
    at emitReadable_ (/Users/hiroyuki.tanjo/lab/webpage-toolkit/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/hiroyuki.tanjo/lab/webpage-toolkit/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/hiroyuki.tanjo/lab/webpage-toolkit/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/hiroyuki.tanjo/lab/webpage-toolkit/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/hiroyuki.tanjo/lab/webpage-toolkit/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/Users/hiroyuki.tanjo/lab/webpage-toolkit/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
```

**Comment by austinpray** [comment]
Getting the same over at https://github.com/roots/sage/blob/49c310b2c653d7f3d33ae0095125c54fc40fd0f0/gulpfile.js#L128

**Comment by jonambas** [comment]
Getting this error as well.

**Comment by shakyShane** [comment]
Something here I suspect https://github.com/BrowserSync/browser-sync/blob/master/test/specs/api/init.reload.js#L91

**Comment by mahnunchik** [comment]
+1

**Comment by j-kwon** [comment]
+1

**Comment by mehwww** [comment]
+1 same here

**Comment by shakyShane** [comment]
Fixed in 2.6.1

Although, all you guys on the bleeding edge with 2.6.1 should switch to `.stream()` now.

```js
var bs = require("browser-sync").create();

gulp.task('sass', function() {
    return sassStream()
        .pipe(gulp.dest(src.css))
        .pipe(bs.stream({match: "*.css"}));
});
```

**Comment by htanjo** [comment]
Thank you! It works with 2.6.1. :laughing:
And thank you for the suggestion.

**Comment by austinpray** [comment]
Lol sorry for the spam. Took a while to get the formatting matched up on the changelog.

@shakyShane 

Can you help me migrate the below to the new 2.6.0 so I can update the docs? Not really understanding how to use the new .create() syntax.

```js
// Save a reference to the `reload` method
var reload = browserSync.reload;

// Compile SASS & auto-inject into browsers
gulp.task('sass', function () {
    return gulp.src('scss/styles.scss')
        .pipe(sass({includePaths: ['scss']}))
        .pipe(gulp.dest('css'))
        .pipe(reload({stream:true}));
});

// Watch scss AND html files, doing different things with each.
gulp.task('serve', ['sass'], function () {

    // Serve files from the root of this project
    browserSync({
        server: {
            baseDir: "./"
        }
    });

    gulp.watch("scss/*.scss", ['sass']);
    gulp.watch("*.html").on("change", browserSync.reload);
});
```

**Comment by shakyShane** [comment]
hey @austinpray - going forward we'll be advising to always use `.create()` as a reference to a BrowserSync instance instead of calling methods on the module export directly.

```js
// old schoolz
var browserSync = require("browser-sync");

browserSync({
    server: "./"
});


// new hotness
var sync = require("browser-sync").create();

sync.init({
    server: "./"
});

```

This is partly to allow multiple instances with different concerns, something like:

```js
// Create a BrowserSync instance
var bs = require("browser-sync").create();
var bs2 = require("browser-sync").create();

// Listen to change events on HTML and reload
bs.watch("*.html").on("change", bs.reload);
bs2.watch("*.jade").on("change", bs2.reload);

// Provide a callback to capture ALL events to CSS
// files - then filter for 'change' and reload all
// css files on the page.
bs.watch("css/*.css", function (event, file) {
    if (event === "change") {
        bs.reload("*.css");
    }
});

// Now init the BrowserSync server
bs.init({
    server: "./app"
});
```

Even when not doing crazy shiz like this, it's still better to just call `.create()` and have a unique reference
