### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by abe-twtMob** [BrowserSync/browser-sync#594]
Out of nowhere my repo is now exploding having changed nothing in my repo's code. Get the following now that i have updated to browser-sync version 2.6.0. Rolled back to 2.5.1 and all runs well again. Thought I would let you know

TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:556:43)
    at Object.<anonymous> (/path_to_app/node_modules/browser-sync/node_modules/http-proxy/lib/http-proxy/index.js:108:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/path_to_app/node_modules/browser-sync/node_modules/http-proxy/lib/http-proxy.js:4:17)
    at Module._compile (module.js:456:26)

**Comment by shinnn** [comment]
Could you try it again with `v2.6.5`?

**Comment by abe-twtMob** [comment]
2.6.5 works. thank you.

**Comment by shinnn** [comment]
@abe-twtMob No problem!
