### ISSUE TITLE
BrowserSync crashing on Gulp task because of WebSockets

### ISSUE THREAD

**Issue by zachfedor** [BrowserSync/browser-sync#611]
I am running browsersync through gulp and it keeps crashing. Here is the output:
```
/Users/zfedor/sites/pokehex/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:222
  if (!this.state.fragmentedOperation) this.unfragmentedBufferPool.reset(true)
                 ^
TypeError: Cannot read property 'fragmentedOperation' of null
    at Receiver.endPacket (/Users/zfedor/sites/pokehex/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:222:18)
    at Receiver.opcodes.1.finish (/Users/zfedor/sites/pokehex/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:394:12)
    at Receiver.<anonymous> (/Users/zfedor/sites/pokehex/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:372:33)
    at Receiver.add (/Users/zfedor/sites/pokehex/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:87:24)
    at Socket.firstHandler (/Users/zfedor/sites/pokehex/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:718:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```
I can't figure out exactly how to reproduce the issue exactly. My watch task spins up fine, brings up a new tab, and connects to the browsersync server. After this, though, it will crash after a small amount of time, maybe a few minutes, maybe instantly. It will always crash if I make any change on a file being watched, starting off another gulp task.

I'm fairly new to gulp and browsersync, so I'll be happy to clarify anything to the best of my ability.

might be related: https://github.com/websockets/ws/issues/366

**Comment by zachfedor** [comment]
I should also add that this is on OSX 10.10.3. Gulp is version 3.8.11 and BrowserSync is 2.6.8.

Here is my [gulpfile](https://github.com/zachfedor/pokehex/blob/master/gulpfile.js)

**Comment by iam4x** [comment]
Same here with https://github.com/iam4x/isomorphic-flux-boilerplate

It happens when we fire a browser reload:

```
/Users/iam4x/savemysmartphone/si-front-users/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:222
  if (!this.state.fragmentedOperation) this.unfragmentedBufferPool.reset(true)
                 ^
TypeError: Cannot read property 'fragmentedOperation' of null
    at Receiver.endPacket (/Users/iam4x/savemysmartphone/si-front-users/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:222:18)
    at Receiver.opcodes.1.finish (/Users/iam4x/savemysmartphone/si-front-users/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:394:12)
    at Receiver.<anonymous> (/Users/iam4x/savemysmartphone/si-front-users/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:372:33)
    at Receiver.add (/Users/iam4x/savemysmartphone/si-front-users/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:87:24)
    at Socket.firstHandler (/Users/iam4x/savemysmartphone/si-front-users/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:718:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at readableAddChunk (_stream_readable.js:145:16)
    at Socket.Readable.push (_stream_readable.js:109:10)
    at TCP.onread (net.js:508:20)
```

**Comment by zachfedor** [comment]
After rolling back to BrowserSync  version `2.6.0`, everything is working as usual. I can keep checking version numbers to see when the issue first started.

**Comment by shakyShane** [comment]
Try 2.7.1

**Comment by zachfedor** [comment]
2.7.1 is working fine. Thanks for the fix!

**Comment by iam4x** [comment]
Yes I can confirm updating to 2.7.1 is working for me too.
