### ISSUE TITLE
Running browserSync.init with proxy option causes an error

### ISSUE THREAD

**Issue by guyzi** [BrowserSync/browser-sync#663]
This is how I run it

```
browserSync.init({
      proxy: 'localhost:8080'      
    });
```

This is the error

```/home/guy/code/CPSPA/node_modules/browser-sync/lib/hooks.js:64
                    initial = initial.push(result);
                                      ^
TypeError: Object function serveBsJavascriptfile(req, res, next) {
            if (req.url.indexOf(scriptPath) > -1) {
                res.writeHead(200, {"Content-Type": "text/javascript"});
                return res.end(scripts);
            }
            next();
        } has no method 'push'
  at [object Object].<anonymous> (/home/guy/code/CPSPA/node_modules/browser-sync/lib/hooks.js:64:39)
  at /home/guy/code/CPSPA/node_modules/lodash/index.js:2781:23
  at baseEach (/home/guy/code/CPSPA/node_modules/lodash/index.js:1826:13)
  at Function.forEach (/home/guy/code/CPSPA/node_modules/lodash/index.js:5953:11)
  at [object Object].module.exports.server:middleware (/home/guy/code/CPSPA/node_modules/browser-sync/lib/hooks.js:51:11)
  at [object Object].EasyExtender.hook (/home/guy/code/CPSPA/node_modules/browser-sync/node_modules/easy-extender/index.js:196:29)
  at getPluginMiddleware (/home/guy/code/CPSPA/node_modules/browser-sync/lib/server/proxy-server.js:64:29)
  at getOptions (/home/guy/code/CPSPA/node_modules/browser-sync/lib/server/proxy-server.js:44:53)
  at createProxyServer (/home/guy/code/CPSPA/node_modules/browser-sync/lib/server/proxy-server.js:23:16)
  at createServer (/home/guy/code/CPSPA/node_modules/browser-sync/lib/server/index.js:51:41)
  at module.exports.plugin (/home/guy/code/CPSPA/node_modules/browser-sync/lib/server/index.js:13:22)
  at Object.module.exports.startServer [as fn] (/home/guy/code/CPSPA/node_modules/browser-sync/lib/async.js:132:52)
  at /home/guy/code/CPSPA/node_modules/browser-sync/lib/browser-sync.js:133:14
  at iterate (/home/guy/code/CPSPA/node_modules/browser-sync/node_modules/async-each-series/index.js:8:5)
  at /home/guy/code/CPSPA/node_modules/browser-sync/node_modules/async-each-series/index.js:16:16
  at executeTask (/home/guy/code/CPSPA/node_modules/browser-sync/lib/browser-sync.js:154:13)
  at Object.module.exports.mergeMiddlewares [as fn] (/home/guy/code/CPSPA/node_modules/browser-sync/lib/async.js:112:16)
  at /home/guy/code/CPSPA/node_modules/browser-sync/lib/browser-sync.js:133:14
  at iterate (/home/guy/code/CPSPA/node_modules/browser-sync/node_modules/async-each-series/index.js:8:5)
  at /home/guy/code/CPSPA/node_modules/browser-sync/node_modules/async-each-series/index.js:16:16
  at executeTask (/home/guy/code/CPSPA/node_modules/browser-sync/lib/browser-sync.js:154:13)
  at Object.module.exports.setFileWatchers [as fn] (/home/guy/code/CPSPA/node_modules/browser-sync/lib/async.js:100:9)
  at /home/guy/code/CPSPA/node_modules/browser-sync/lib/browser-sync.js:133:14
  at iterate (/home/guy/code/CPSPA/node_modules/browser-sync/node_modules/async-each-series/index.js:8:5)
  at /home/guy/code/CPSPA/node_modules/browser-sync/node_modules/async-each-series/index.js:16:16
  at executeTask (/home/guy/code/CPSPA/node_modules/browser-sync/lib/browser-sync.js:154:13)
  at Object.module.exports.setInternalEvents [as fn] (/home/guy/code/CPSPA/node_modules/browser-sync/lib/async.js:93:9)
  at /home/guy/code/CPSPA/node_modules/browser-sync/lib/browser-sync.js:133:14
  at iterate (/home/guy/code/CPSPA/node_modules/browser-sync/node_modules/async-each-series/index.js:8:5)
  at /home/guy/code/CPSPA/node_modules/browser-sync/node_modules/async-each-series/index.js:16:16
  at executeTask (/home/guy/code/CPSPA/node_modules/browser-sync/lib/browser-sync.js:154:13)
  at Object.module.exports.setOptions [as fn] (/home/guy/code/CPSPA/node_modules/browser-sync/lib/async.js:65:9)
  at /home/guy/code/CPSPA/node_modules/browser-sync/lib/browser-sync.js:133:14
  at iterate (/home/guy/code/CPSPA/node_modules/browser-sync/node_modules/async-each-series/index.js:8:5)
  at /home/guy/code/CPSPA/node_modules/browser-sync/node_modules/async-each-series/index.js:16:16
  at executeTask (/home/guy/code/CPSPA/node_modules/browser-sync/lib/browser-sync.js:154:13)
  at /home/guy/code/CPSPA/node_modules/browser-sync/lib/async.js:48:17
  at asyncCallback (dns.js:68:16)
  at Object.onanswer [as oncomplete] (dns.js:147:9)
```

This issue seems similar to the issue fixed here
https://github.com/shakyShane/browser-sync-spa/issues/1

I was able to make it work on my machine by editing 
node_modules/browser-sync/lib/snippet.js

```
    getProxyMiddleware: function (scripts, scriptPath) {
        return function serveBsJavascriptfile (req, res, next) {
            if (req.url.indexOf(scriptPath) > -1) {
                res.writeHead(200, {"Content-Type": "text/javascript"});
                return res.end(scripts);
            }
            next();
        };
    },```
```

Into 

```
    getProxyMiddleware: [function (scripts, scriptPath) {
        return function serveBsJavascriptfile (req, res, next) {
            if (req.url.indexOf(scriptPath) > -1) {
                res.writeHead(200, {"Content-Type": "text/javascript"});
                return res.end(scripts);
            }
            next();
        }];
    },
```

**Comment by shinnn** [comment]
I cannot reproduce the error.

```
$ python -m SimpleHTTPServer 8080
Serving HTTP on 0.0.0.0 port 8080 ...
```

```
$ node -e "require('browser-sync').init({proxy: 'localhost:8080'});"
[BS] Proxying: http://localhost:8081
[BS] Access URLs:
 ----------------------------------
       Local: http://localhost:3000
    External: http://10.0.1.3:3000
 ----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.1.3:3001
 ----------------------------------
```

Versions:

```
$ node -v
v2.2.1
$ npm ls browser-sync
test@ /Users/Shinnosuke/test
└── browser-sync@2.7.6 
```

**Comment by shinnn** [comment]
@guyzi When does the error occur? Initialize the server, or reload?

**Comment by shinnn** [comment]
@guyzi Feel free to comment about details if you still running into this problem.

**Comment by guyzi** [comment]
Hi @shinnn, thank you for your reply.

I am able to recreate this by running this yeoman generator (default options)
https://github.com/Swiip/generator-gulp-angular

And changing this in gulp/server.js
```
 browserSync.instance = browserSync.init({
      startPath: '/',
      server: server,      
      browser: browser
    });
  }
```

Into
```
    browserSync.instance = browserSync.init({
      proxy: 'localhost:8080',
    });
  }
```

Then running `gulp serve` causes the above mentioned error

**Comment by shinnn** [comment]
Confirmed.

**Comment by shakyShane** [comment]
@shinnn - confirmed also.

the `server:middleware` hook expects an array as the initial value, but [here](https://github.com/BrowserSync/browser-sync/blob/master/lib/server/proxy-server.js#L83) we only pass a single function.

fix coming shortly

**Comment by shakyShane** [comment]
Thank @guyzi for reporting, & @shinnn for confirming. Will push out  patch release following CI passes

**Comment by shakyShane** [comment]
browser-sync@2.7.7

**Comment by shakyShane** [comment]
@guyzi also worth noting though, if you're using the proxy option, then you shouldn't be using 'browser-sync-spa' with it (as it's meant for static servers)

**Comment by guyzi** [comment]
Thanks for the information, I will remove it. And thanks for the fix
