### ISSUE TITLE
Couldn't install on windows 8 even after installing vs2013 express for desktop

### ISSUE THREAD

**Issue by nitinsurana** [BrowserSync/browser-sync#759]
```
npm install -g browser-sync
npm install -g browser-sync --msvs_version=2013
```
Both of the above commands fail.

http://screencast.com/t/WjqZJnGEZ7

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  validation.cc
     Creating library C:\Users\Nitin\AppData\Roaming\npm\node_modules\browser-sync\node_modules\socket.io\node_modules\
  socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate\build\Release\validation.l
  ib and object C:\Users\Nitin\AppData\Roaming\npm\node_modules\browser-sync\node_modules\socket.io\node_modules\socket
  .io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate\build\Release\validation.exp
  Generating code
  Finished generating code
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(607,5): error MSB6003: The specified
 task executable "link.exe" could not be run. C:\Users\Nitin\AppData\Roaming\npm\node_modules\browser-sync\node_modules
\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate\buil
d\Release\obj\validation\validation.tlog\link-cvtres.write.[ID].tlog [C:\Users\Nitin\AppData\Roaming\npm\node_modules\b
rowser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_mod
ules\utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Nitin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib
\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\Nitin\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-g
yp.js" "rebuild"
gyp ERR! cwd C:\Users\Nitin\AppData\Roaming\npm\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-
client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
```

Anything I'm missing or is the latest build doesn't work on Windows 8 ?

**Comment by ramasilveyra** [comment]
I think this is a problem of [ws](https://github.com/websockets/ws) and [node-gyp](https://github.com/TooTallNate/node-gyp).

**Comment by shinnn** [comment]
And [utf-8-validate](https://github.com/websockets/utf-8-validate).

**Comment by davidmmemorandum** [comment]
What is the solution to avoid this kind of error? I have the same one after installing Visual Studio 2013 Update 5. I have tried "npm install -g browser-sync --msvs_version=2013", but no success. I also tried to install modules mentioned above: ws, node-gyp, utf-validate, but no way. Thanks!

**Comment by nitinsurana** [comment]
I don't know the exact steps, but I kept trying and installing utf8-validate separately and installing python and then it worked.
