### ISSUE TITLE
Browser sync throws a TypeError on init

### ISSUE THREAD

**Issue by agconti** [BrowserSync/browser-sync#761]
BrowserSync throws a `TypeError` when it attempts to reload:

```bash
[12:02:53] TypeError: undefined is not a function
    at Object.init (/Users/conti/dev/foodjournal-web/node_modules/browser-sync/lib/public/init.js:25:25)
    at Gulp.<anonymous> (/Users/conti/dev/foodjournal-web/gulpfile.js:39:15)
    at module.exports (/Users/conti/dev/foodjournal-web/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/conti/dev/foodjournal-web/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/conti/dev/foodjournal-web/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/conti/dev/foodjournal-web/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at Gulp.<anonymous> (/Users/conti/dev/foodjournal-web/node_modules/gulp/index.js:36:18)
    at Gaze.<anonymous> (/Users/conti/dev/foodjournal-web/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:18:14)
    at Gaze.emit (events.js:110:17)
    at Gaze.emit (/Users/conti/dev/foodjournal-web/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:129:32)
```

That points to the `browser-sync` gulp task:

```js
gulp.task('browser-sync', function () {
  browserSync.init({
     server: {
       baseDir: "./public"
     }
   })
})
```

Any idea what could be going wrong? I'm using version `2.8.2`.

**Comment by shakyShane** [comment]
Make sure you call `create()` first.

```js
var browserSync = require('browser-sync').create();
var gulp = require('gulp');

gulp.task('browser-sync', function () {
  browserSync.init({
     server: {
       baseDir: "./public"
     }
   })
})

**Comment by agconti** [comment]
@shakyShane I'm calling `create()`. Here's my gulpfile for reference: 


```js

var gulp = require('gulp')
  , browserSync = require('browser-sync').create()
  , reload = browserSync.reload
  , changed = require('gulp-changed')
  , autoprefixer = require('gulp-autoprefixer')
  , sass = require('gulp-sass')
  , uglify = require('gulp-uglify')
  , flatten = require('gulp-flatten')
  , concat = require('gulp-concat')
  , gulpNgConfig = require('gulp-ng-config')

  // Path config
  , outputDir = './public'
  , scssSrc = outputDir + '/admin/main.scss'
  , jsSrc = ['/admin/app.js', '/admin/**/index.js','/admin/**/*.js'].map(function(path){
      return outputDir + path
    })

  // App config
  , configModule = 'config'
  , parseConfig = './config.json'
  , parseConfigOutput =  outputDir + '/admin/config/'
  , ngConfigOptionsDev = new NgConfigOptions('dev')
  , ngConfigOptionsProd = new NgConfigOptions('prod')


/**
 * Class for configuring app enviorments.
 * @param {string} env -- the target enviorment
 * @constructor
 */
function NgConfigOptions(env){
  this.environment = env || 'dev'
  this.createModule = false
  this.wrap = ';(function () {\n <%= module %> \n})()'
}

gulp.task('browser-sync', function () {
  browserSync.init({
     server: {
       baseDir: outputDir
     }
   })
})

gulp.task('sass', function () {
  return gulp.src(scssSrc)
    .pipe(changed(outputDir))
    .pipe(autoprefixer('last 2 versions'))
    .pipe(sass({errLogToConsole: true}).on('error', console.error.bind(console)))
    .pipe(gulp.dest(outputDir))
    .pipe(browserSync.stream())
})

gulp.task('config:dev', function () {
  return gulp.src(parseConfig)
    .pipe(gulpNgConfig(configModule, ngConfigOptionsDev))
    .pipe(gulp.dest(parseConfigOutput))
    .pipe(browserSync.stream())
})


gulp.task('config:prod', function () {
  return gulp.src(parseConfig)
    .pipe(gulpNgConfig(configModule,  ngConfigOptionsProd))
    .pipe(gulp.dest(parseConfigOutput))
    .pipe(browserSync.stream())
})


/**
 * Concatenates, minifies, and outputs site's javascript.
 * @return {stream}
 */
function buildJs() {
  return gulp.src(jsSrc)
    .pipe(changed(outputDir))
    .pipe(concat('main.min.js'))
    .pipe(uglify())
    .pipe(flatten())
    .pipe(gulp.dest(outputDir))
    .pipe(browserSync.stream())
}

gulp.task('build:js:dev', ['config:dev'], buildJs)
gulp.task('build:js:prod', ['config:prod'], buildJs)

gulp.task('build:dev', ['build:js:dev', 'sass'])
gulp.task('build:prod', ['build:js:prod', 'sass'])

gulp.task('default', ['build:js:dev', 'sass', 'browser-sync'], function(){
  gulp.watch(['./public/**/*.scss'], ['sass'])
  gulp.watch([jsSrc], ['build:js:dev'])
  gulp.watch(["./public/**/*.html"], [reload])
})

```

**Comment by agconti** [comment]
Can we reopen this issue?

**Comment by shakyShane** [comment]
If you can provide a sample repo showing the issue, then sure :)

**Comment by Scrivs** [comment]
I'm encountering the same issue when I try to run browsersync off the local filesystem. When I use Vagrant and a domain in my gulpfile everything works fine, but if I try to go through a proxy it will load the first time and then break on any changes I make to my styles afterwards.

Here is a very basic one page site repo that shows the issue: https://github.com/MakersCabin/LearnCSS

**Comment by BirgitPohl** [comment]
I'm trying to add it into a watcher that converts Coffeescript to Javascript.
[Here is my repo where it first occured.](https://github.com/BirgitPohl/GulpTask/blob/59bbc2b7fc29fcd02af53a33596188ce67275a85/build/gulpfile.coffee)
[As recommended above](https://github.com/BrowserSync/browser-sync/issues/761#issuecomment-132120816), I put the create method before the gulp variable. The error message is the same.

**Comment by csaltrev** [comment]
I'm still having the same issue. Here's my gulpfile:
```
const gulp = require('gulp');
const sass = require('gulp-sass');
const browserSync = require('browser-sync').create();

gulp.task('sass', () => {
    gulp.src('app/sass/**/*.scss')
        .pipe(sass())
        .pipe(gulp.dest('app/css'))
        .pipe(browserSync.stream());
});

gulp.task('browser-sync', () => {
    browserSync.init({
        server: {
            baseDir: 'app'
        }
    });
});

gulp.task('serve', ['sass', 'browser-sync'], () => {
    gulp.watch('app/sass/**/*.scss', ['sass']);
});
```

**Comment by DevNIX** [comment]
I'm also affected by this bug, only when I inclide this Javascript, I have no idea where could be the problem: http://imulus.github.io/retinajs/

**Comment by DevNIX** [comment]
I could get it working following the #1234 issue
