### ISSUE TITLE
BrowserSync proxy port 80 asking for sudo

### ISSUE THREAD

**Issue by jrock2004** [BrowserSync/browser-sync#786]
So I setup BrowserSync to proxy to port 80 as that is where my site is running. When I run the watch gulp task, its giving me an error

```shell
gulp watch
[22:51:02] Using gulpfile ~/Development/lcac/gulpfile.js
[22:51:02] Starting 'browserSync'...
[22:51:02] Finished 'browserSync' after 43 ms
[22:51:02] Starting 'watch'...
[22:51:02] Finished 'watch' after 27 ms
events.js:85
  throw er; // Unhandled 'error' event
            ^
Error: listen EACCES
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1139:19)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at module.exports.plugin (/Users/jcostanzo/Development/lcac/node_module
s/browser-sync/lib/server/index.js:24:25)
    at Object.module.exports.startServer [as fn] (/Users/jcostanzo/Developm
ent/lcac/node_modules/browser-sync/lib/async.js:216:52)
    at /Users/jcostanzo/Development/lcac/node_modules/browser-sync/lib/brow
ser-sync.js:149:14
    at iterate (/Users/jcostanzo/Development/lcac/node_modules/browser-sync
/node_modules/async-each-series/index.js:8:5)
    at /Users/jcostanzo/Development/lcac/node_modules/browser-sync/node_mod
ules/async-each-series/index.js:16:16
    at executeTask (/Users/jcostanzo/Development/lcac/node_modules/browser-
sync/lib/browser-sync.js:170:13)
```

Reading your documentation it states its possibly due to npm permissions

```shell
$ ls -l /usr/local
total 80
-rw-r--r--    1 jcostanzo  admin   3161 Aug 24 16:32 CODEOFCONDUCT.md
-rw-r--r--    1 jcostanzo  admin   1103 Aug 24 16:32 CONTRIBUTING.md
drwxr-xr-x   30 jcostanzo  admin   1020 Aug 24 18:51 Cellar
-rw-r--r--    1 jcostanzo  admin   1241 Aug 24 16:32 LICENSE.txt
drwxr-xr-x   11 jcostanzo  admin    374 Aug 24 17:27 Library
-rw-r--r--    1 jcostanzo  admin   2319 Aug 24 16:32 README.md
-rw-r--r--    1 jcostanzo  admin  23801 Aug 24 16:32 SUPPORTERS.md
drwxr-xr-x  134 jcostanzo  admin   4556 Aug 24 18:52 bin
drwxr-xr-x    9 jcostanzo  admin    306 Aug 24 17:39 etc
drwxr-xr-x   40 jcostanzo  admin   1360 Aug 24 18:51 include
drwxr-xr-x   67 jcostanzo  admin   2278 Aug 24 18:51 lib
drwxr-xr-x   30 jcostanzo  admin   1020 Aug 24 18:51 opt
drwxr-xr-x    4 jcostanzo  admin    136 Aug 24 17:44 sbin
drwxr-xr-x   19 jcostanzo  admin    646 Aug 24 18:51 share
drwxr-xr-x    6 jcostanzo  admin    204 Aug 24 17:44 var
```

Here is my gulp file

```js
var gulp        = require('gulp'),
		gutil       = require('gulp-util'),
		gulpFilter  = require('gulp-filter'),
		bowerMain   = require('main-bower-files'),
		concat      = require('gulp-concat'),
		uglify      = require('gulp-uglify'),
		rename      = require('gulp-rename'),
		sourcemaps  = require('gulp-sourcemaps'),
		less        = require('gulp-less'),
		watch       = require('gulp-watch'),
		browserSync = require('browser-sync');

// Default tasks
gulp.task('default', ['bower', 'less', 'js']);

// Starts the browser sync server
gulp.task('browserSync', function() {
	browserSync({
		proxy: 'lcac.dev',
		port: '80'
	});
});

// Starts the browser sync server then watches our files
gulp.task('watch', ['browserSync'], function() {
	gulp.watch('src/less/*.less', ['less']);
	gulp.watch('public/**/*.php').on('change', browserSync.reload);
	gulp.watch('src/js/**/*.js', ['js-watch']);
});

// Wrapper for watching js to reload the pages
gulp.task('js-watch', ['js'], browserSync.reload);

// Grabs our files from bower_components
gulp.task('bower', function() {
	var jsFilter  = gulpFilter('*.js', {restore: true});

	return gulp.src(bowerMain())
		// JS
		.pipe(jsFilter)
		.pipe(concat('base.js'))
		.pipe(gulp.dest('./public/js'))
		.pipe(uglify())
		.pipe(rename({
			suffix: '.min'
		}))
		.pipe(gulp.dest('./public/js'))
		.pipe(jsFilter.restore)

		gutil.log(bowerMain());
});

gulp.task('less', function() {
	return gulp.src('./src/less/**/*.less')
		.pipe(sourcemaps.init())	
		.pipe(less({
			paths: ["bower_components/bootstrap/less"]
		}))
		.pipe(concat("styles.min.css"))
		.pipe(sourcemaps.write())
		.pipe(gulp.dest('./public/css'))
		.pipe(browserSync.stream())
});

gulp.task('js', function() {
	return gulp.src('./src/js/*.js')	
		.pipe(concat("scripts.js"))
		.pipe(gulp.dest('./public/js'))
		.pipe(uglify())
		.pipe(rename({
			suffix: '.min'
		}))
		.pipe(gulp.dest('./public/js'))
});

```

Is there something I am doing wrong?

**Comment by shakyShane** [comment]
Remove the `port` option from your Browsersync config. It's 80 by default.

http://stackoverflow.com/questions/9164915/node-js-eacces-error-when-listening-on-most-ports

**Comment by splinter** [comment]
You need to run the gulp task as sudo as the OS restricts the first 1024 ports to the root user [1].

[1] http://unix.stackexchange.com/questions/16564/why-are-the-first-1024-ports-restricted-to-the-root-user-only
