### ISSUE TITLE
Error when i create new some folders or files

### ISSUE THREAD

**Issue by wbye** [BrowserSync/browser-sync#789]
when i use browser-sync with gulp,my watch files changes ,my chrome browser can refresh page normally;but  if I create some new folders or files, the browser-sync throw a error like this:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: watch ENOENT
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at Gaze._watchDir (/Users/ywbshiwo/Work/fix-styles/console/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
    at /Users/ywbshiwo/Work/fix-styles/console/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/Users/ywbshiwo/Work/fix-styles/console/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /Users/ywbshiwo/Work/fix-styles/console/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
    at /Users/ywbshiwo/Work/fix-styles/console/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/Users/ywbshiwo/Work/fix-styles/console/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /Users/ywbshiwo/Work/fix-styles/console/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11

how could i  solve this problem ?

**Comment by shinnn** [comment]
> /Users/ywbshiwo/Work/fix-styles/console/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30

That's not a Browsersync issue.
