### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by jrock2004** [BrowserSync/browser-sync#811]
Been using browser-sync in Windows just fine. I moved over to my linux machine and when I run gulp, which starts browser-sync, I get errors

```shell
jcostanzo at surfacepro in ~/Development/Work/jda-lookup (master●)
$ gulp
[01:16:53] Using gulpfile ~/Development/Work/jda-lookup/gulpfile.js
[01:16:53] Starting 'bower'...
[01:16:53] Starting 'nodemon'...
[01:16:53] Starting 'watch'...
[01:16:53] Finished 'watch' after 8.27 ms
[01:16:53] [nodemon] v1.4.1
[01:16:53] [nodemon] to restart at any time, enter `rs`
[01:16:53] [nodemon] watching: *.*
[01:16:53] [nodemon] starting `node bin/www`
[01:16:53] Finished 'nodemon' after 39 ms
[01:16:53] Starting 'browser-sync'...
[01:16:53] Finished 'browser-sync' after 83 ms
[BS] Proxying: http://localhost:3000
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:7000
    External: http://192.168.0.114:7000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.114:3001
 --------------------------------------
[BS] Watching files...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

jcostanzo at surfacepro in ~/Development/Work/jda-lookup (master●)
$ GET / 200 390.303 ms - 2226
```

Here is my gulpfile

```js
var gulp 		= require('gulp'),
	gutil 		= require('gulp-util'),
	filter 		= require('gulp-filter'),
	bower   	= require('main-bower-files'),
	concat      = require('gulp-concat'),
	uglify      = require('gulp-uglify'),
	rename      = require('gulp-rename'),
	sourcemaps  = require('gulp-sourcemaps'),
	sass 		= require('gulp-sass'),
	watch       = require('gulp-watch'),
	browserSync = require('browser-sync'),
	nodemon		= require('gulp-nodemon');
	
gulp.task('default', ['bower', 'browser-sync', 'watch']);

gulp.task('browser-sync', ['nodemon'], function() {
	browserSync.init(null, {
		proxy: "http://localhost:3000",
        files: ["public/**/*.*"],
        browser: "google chrome",
        port: 7000,
	});
});

gulp.task('nodemon', function (cb) {
	var started = false;
	
	return nodemon({
		script: 'bin/www'
	}).on('start', function () {
		// to avoid nodemon being started multiple times
		if (!started) {
			cb();
			started = true; 
		} 
	});
});

gulp.task('watch', function() {
	gulp.watch('views/*.jade').on('change', browserSync.reload);
	gulp.watch('assets/sass/**/*.scss', ['sass']);
});

gulp.task('sass', function() {
	return gulp.src('./assets/sass/styles.scss')
		.pipe(sourcemaps.init())
		.pipe(sass({
			includePaths: ['bower_components/bootstrap/scss']
		}))
		.pipe(concat('styles.css'))
		.pipe(sourcemaps.write())
		.pipe(gulp.dest('./public/stylesheets'))
		.pipe(browserSync.stream());
});

gulp.task('bower', function() {
	var jsFilter  = filter('*.js', {restore: true});

	return gulp.src(bower())
		// JS
		.pipe(jsFilter)
		.pipe(concat('base.js'))
		.pipe(gulp.dest('./public/javascripts'))
		.pipe(uglify())
		.pipe(rename({
			suffix: '.min'
		}))
		.pipe(gulp.dest('./public/javascripts'))
		.pipe(jsFilter.restore);
});
```

If I do not use browser-sync, I can run nodemon via command line and it starts up

**Comment by shakyShane** [comment]
@jrock2004 please try v2.9.3

If this problem still occurs, please provide a tiny sample project showing this bug and I'll happily re-open the issue and help to resolve it.

**Comment by claudiomedina** [comment]
@jrock2004 did you found a solution?

**Comment by mobula** [comment]
A solution from issue #732:   `process.platform === 'linux' ? 'google-chrome' : 'google chrome'`
```
gulp.task('browser-sync', ['nodemon'], function() {
    browserSync.init(null, {
        proxy: "http://localhost:3000",
        files: ["public/**/*.*"],
        browser: process.platform === 'linux' ? 'google-chrome' : 'google chrome',
        port: 7000,
    });
});
```

**Comment by tarvos21** [comment]
Take care of the files not related, I solve this by removing some directories out of the watched folder.
