### ISSUE TITLE
Fatal error: Module version mismatch. Expected 46, got 14.

### ISSUE THREAD

**Issue by KingScooty** [BrowserSync/browser-sync#833]
After installing Node 4.1.0, and npm 3.3.4, i'm guessing this weird error when using browser sync:

```bash
Running "browserSync:dev" (browserSync) task
Fatal error: Module version mismatch. Expected 46, got 14.
Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/KingScooty/Desktop/live-styleguide/node_modules/bs-html-injector/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/KingScooty/Desktop/live-styleguide/node_modules/bs-html-injector/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
```

**Comment by shakyShane** [comment]
Specific to `bs-html-injector` (or more likely jsdom).

Please move this issue report to either/both of those projects :)
