### ISSUE TITLE
"AssertionError" when using an IOS 9 device with adblocker

### ISSUE THREAD

**Issue by tinusn** [BrowserSync/browser-sync#843]
FYI, I just experienced the first problem with using an adblocker in safari (Crystal) when used with browser-sync, because browser-sync errors out with the following error:
```
[BS] Access URLs:                                         
 --------------------------------------                   
       Local: http://localhost:3000                       
    External: http://192.168.0.195:3000                   
 --------------------------------------                   
          UI: http://localhost:3001                       
 UI External: http://192.168.0.195:3001                   
 --------------------------------------                   
[BS] Serving files from: app                              
                                                          
assert.js:89                                              
  throw new assert.AssertionError({                       
  ^                                                       
AssertionError: false == true                             
    at ServerResponse.resOnFinish (_http_server.js:473:7) 
    at emitNone (events.js:67:13)                         
    at ServerResponse.emit (events.js:166:7)              
    at finish (_http_outgoing.js:526:10)                  
    at doNTCallback0 (node.js:407:9)                      
    at process._tickCallback (node.js:336:13)             
```
If I disable the adblocker, then everything works fine.

**Comment by shakyShane** [comment]
Browsersync, being a development-only tool, cannot attempt to handle every situation/browser extension.

I would be willing to fix this however if you provide more details about this problem such as a sample project
