### ISSUE TITLE
Error: Cannot find module 'browser-sync'

### ISSUE THREAD

**Issue by sajjadmurtaza-ror** [BrowserSync/browser-sync#866]
➜  my-project  gulp serve
module.js:338
    throw err;
          ^
Error: Cannot find module 'browser-sync'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/sajad/p_projects/my-project/gulpfile.js:17:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by shakyShane** [comment]
https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md#-tips-for-a-creating-a-great-issue-report
