### ISSUE TITLE
Error: Cannot find module 'dateformat'

### ISSUE THREAD

**Issue by paulmist** [BrowserSync/browser-sync#930]
After install and config running 'gulp browser-sync' throws the following error:
```
module.js:338
    throw err;
    ^

Error: Cannot find module 'dateformat'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/gulp-util/index.js:5:9)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```
gulpfile.js config is:
```
var gulp        = require('gulp'),
	browserSync = require('browser-sync');

gulp.task('browser-sync', function() {
    browserSync.init({
        server: {
            baseDir: "src/"
        }
    });
});
```

**Comment by shakyShane** [comment]
This is not a bug with Browsersync, the error suggests it's to do with gulp-util. Try wiping your node_modules dir and re-installing. Also check you have locally installed al the modules you need :)
